// Systems-Modeler-Pro PR56 bounded Groovy-compatible complete demonstration.
// Organized to mirror a clean MBSE repository: common definitions, requirements, use cases,
// structure, behavior, parametrics/analysis, and runtime configurations.
// Every authored Activity, State Machine, and Interaction below has a corresponding diagram.
// Reapplying the same namespace/external IDs is intended to update/idempotently reuse semantics.
modelScript('''
{
  "source_namespace": "demo:complete-vehicle:v2",
  "operations": [
    {"op":"element","external_id":"PKG","kind":"Package","name":"Complete Vehicle Demonstration","owner":"$root","documentation":"End-to-end SysML demonstration model for import, execution, persistence, export, and re-import testing."},
    {"op":"element","external_id":"PKG_COMMON","kind":"Package","name":"00 Common Library","owner":"handle:PKG","documentation":"Reusable primitive types and interface definitions shared across the demonstration model."},
    {"op":"element","external_id":"PKG_TYPES","kind":"Package","name":"Types","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_INTERFACES","kind":"Package","name":"Interfaces","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_REQ","kind":"Package","name":"10 Requirements and Verification","owner":"handle:PKG","documentation":"Text requirements, verification TestCases, and requirement traceability relationships."},
    {"op":"element","external_id":"PKG_UC","kind":"Package","name":"20 Use Cases","owner":"handle:PKG","documentation":"Actors, Use Cases, and Use Case relationships."},
    {"op":"element","external_id":"PKG_STRUCTURE","kind":"Package","name":"30 Structure","owner":"handle:PKG","documentation":"System and component definitions plus internal structure presentations."},
    {"op":"element","external_id":"PKG_BEHAVIOR","kind":"Package","name":"40 Behavior","owner":"handle:PKG","documentation":"Behavior is partitioned into Activities, State Machines, Interactions, and reusable Signals/Events."},
    {"op":"element","external_id":"PKG_ACTIVITIES","kind":"Package","name":"Activities","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_STATES","kind":"Package","name":"State Machines","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_INTERACTIONS","kind":"Package","name":"Interactions","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_SIGNALS","kind":"Package","name":"Signals and Events","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_PARAM","kind":"Package","name":"50 Parametrics and Analysis","owner":"handle:PKG","documentation":"Reusable constraints and executable parametric analysis definitions."},
    {"op":"element","external_id":"PKG_CONFIG","kind":"Package","name":"60 Configurations and Runtime","owner":"handle:PKG","documentation":"Runtime occurrence/configuration examples used to demonstrate structural execution isolation."},
    {"op":"element","external_id":"REAL","kind":"PrimitiveType","name":"Real","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"BOOL","kind":"PrimitiveType","name":"Boolean","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"VEH","kind":"Block","name":"ElectricVehicle","owner":"handle:PKG_STRUCTURE","documentation":"System context for the demonstration."},
    {"op":"element","external_id":"COMP","kind":"Block","name":"VehicleComponent","owner":"handle:PKG_STRUCTURE","documentation":"Common component specialization root."},
    {"op":"element","external_id":"CTRL","kind":"Block","name":"VehicleController","owner":"handle:PKG_STRUCTURE"},
    {"op":"element","external_id":"BAT","kind":"Block","name":"BatteryPack","owner":"handle:PKG_STRUCTURE"},
    {"op":"element","external_id":"MOTOR","kind":"Block","name":"TractionMotor","owner":"handle:PKG_STRUCTURE"},
    {"op":"element","external_id":"HMI","kind":"Block","name":"DriverInterface","owner":"handle:PKG_STRUCTURE"},
    {"op":"element","external_id":"POWER_IF","kind":"InterfaceBlock","name":"PowerInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"COMMAND_IF","kind":"InterfaceBlock","name":"CommandInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"FLEET","kind":"Block","name":"Fleet","owner":"handle:PKG_CONFIG","documentation":"Structural execution root containing two independent ElectricVehicle occurrences."},
    {"op":"element","external_id":"P_VEHA","kind":"PartProperty","name":"vehicleA","owner":"handle:FLEET","type_ref":"handle:VEH","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_VEHB","kind":"PartProperty","name":"vehicleB","owner":"handle:FLEET","type_ref":"handle:VEH","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"POWER_FLOW","kind":"FlowProperty","name":"power","owner":"handle:POWER_IF","type_ref":"handle:REAL","flow_direction":"Out"},
    {"op":"element","external_id":"CTRL_SERVICE","kind":"FullPort","name":"service","owner":"handle:CTRL","type_ref":"handle:COMMAND_IF"},
    {"op":"element","external_id":"R_HMI","kind":"ReferenceProperty","name":"maintenanceConsole","owner":"handle:VEH","type_ref":"handle:HMI","multiplicity":{"lower":0,"upper":1}},
    {"op":"element","external_id":"CTRL_POWER","kind":"ProxyPort","name":"power","owner":"handle:CTRL","type_ref":"handle:POWER_IF"},
    {"op":"element","external_id":"CTRL_CMD","kind":"ProxyPort","name":"command","owner":"handle:CTRL","type_ref":"handle:COMMAND_IF"},
    {"op":"element","external_id":"BAT_POWER","kind":"ProxyPort","name":"powerOut","owner":"handle:BAT","type_ref":"handle:POWER_IF"},
    {"op":"element","external_id":"MOTOR_POWER","kind":"ProxyPort","name":"powerIn","owner":"handle:MOTOR","type_ref":"handle:POWER_IF","is_conjugated":true},
    {"op":"element","external_id":"P_CTRL","kind":"PartProperty","name":"controller","owner":"handle:VEH","type_ref":"handle:CTRL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BAT","kind":"PartProperty","name":"battery","owner":"handle:VEH","type_ref":"handle:BAT","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_MOTOR","kind":"PartProperty","name":"motor","owner":"handle:VEH","type_ref":"handle:MOTOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_HMI","kind":"PartProperty","name":"driverInterface","owner":"handle:VEH","type_ref":"handle:HMI","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_MASS","kind":"ValueProperty","name":"mass","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"1800","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_ACCEL","kind":"ValueProperty","name":"acceleration","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"2.5","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_FORCE","kind":"ValueProperty","name":"tractiveForce","owner":"handle:VEH","type_ref":"handle:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"OP_START","kind":"Operation","name":"startVehicle","owner":"handle:CTRL"},
    {"op":"element","external_id":"PAR_MODE","kind":"Parameter","name":"driveMode","owner":"handle:OP_START","type_ref":"handle:REAL","parameter_direction":"In","default_value":"1.0","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"SIG_START","kind":"Signal","name":"StartCommand","owner":"handle:PKG_SIGNALS"},
    {"op":"element","external_id":"SIG_READY","kind":"Signal","name":"VehicleReady","owner":"handle:PKG_SIGNALS"},
    {"op":"element","external_id":"SIG_STOP","kind":"Signal","name":"StopCommand","owner":"handle:PKG_SIGNALS"},
    {"op":"element","external_id":"SIG_POWER","kind":"Signal","name":"PowerEnable","owner":"handle:PKG_SIGNALS"},
    {"op":"element","external_id":"SIG_POWER_OK","kind":"Signal","name":"PowerAvailable","owner":"handle:PKG_SIGNALS"},
    {"op":"element","external_id":"REC_START","kind":"Reception","name":"startCommand","owner":"handle:CTRL","type_ref":"handle:SIG_START"},
    {"op":"element","external_id":"REC_STOP","kind":"Reception","name":"stopCommand","owner":"handle:CTRL","type_ref":"handle:SIG_STOP"},
    {"op":"element","external_id":"REQ_START","kind":"Requirement","name":"CommandedStartup","owner":"handle:PKG_REQ","requirement_id":"REQ-001","requirement_text":"The electric vehicle shall transition from Off to Ready in response to a valid start command."},
    {"op":"element","external_id":"REQ_POWER","kind":"Requirement","name":"PowerDelivery","owner":"handle:PKG_REQ","requirement_id":"REQ-002","requirement_text":"The battery subsystem shall provide traction power to the motor when commanded."},
    {"op":"element","external_id":"REQ_TRACE","kind":"Requirement","name":"StartupLatency","owner":"handle:PKG_REQ","requirement_id":"REQ-003","requirement_text":"The vehicle shall complete commanded startup within the allocated startup interval."},
    {"op":"element","external_id":"TC_START","kind":"TestCase","name":"VerifyCommandedStartup","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"TC_POWER","kind":"TestCase","name":"VerifyPowerDelivery","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"DRIVER","kind":"Actor","name":"Driver","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"TECH","kind":"Actor","name":"ServiceTechnician","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"UC_START","kind":"UseCase","name":"StartVehicle","owner":"handle:PKG_UC","extension_points":["startup complete"]},
    {"op":"element","external_id":"UC_DIAG","kind":"UseCase","name":"RunDiagnostics","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"CB_FORCE","kind":"ConstraintBlock","name":"ForceBalance","owner":"handle:PKG_PARAM"},
    {"op":"element","external_id":"CP_M","kind":"ConstraintParameter","name":"m","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CP_A","kind":"ConstraintParameter","name":"a","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CP_F","kind":"ConstraintParameter","name":"f","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"C_FORCE","kind":"ConstraintProperty","name":"forceBalance","owner":"handle:VEH","type_ref":"handle:CB_FORCE","multiplicity":{"lower":1,"upper":1}},
    {"op":"relationship","external_id":"A_VEH_CTRL","kind":"Association","source":"handle:VEH","target":"handle:CTRL","owner":"handle:PKG_STRUCTURE","name":"controllerArchitecture","source_end":{"role_name":"vehicle","multiplicity":{"lower":1,"upper":1},"navigable":false,"aggregation":"None"},"target_end":{"role_name":"controllerType","multiplicity":{"lower":1,"upper":1},"navigable":true,"aggregation":"None"}},
    {"op":"relationship","external_id":"G_CTRL","kind":"Generalization","source":"handle:CTRL","target":"handle:COMP","owner":"handle:PKG_STRUCTURE"},
    {"op":"relationship","external_id":"G_BAT","kind":"Generalization","source":"handle:BAT","target":"handle:COMP","owner":"handle:PKG_STRUCTURE"},
    {"op":"relationship","external_id":"G_MOTOR","kind":"Generalization","source":"handle:MOTOR","target":"handle:COMP","owner":"handle:PKG_STRUCTURE"},
    {"op":"relationship","external_id":"DEP_POWER","kind":"Dependency","source":"handle:CTRL","target":"handle:BAT","owner":"handle:PKG_STRUCTURE","name":"requestsPower"},
    {"op":"relationship","external_id":"SAT_START","kind":"Satisfy","source":"handle:CTRL","target":"handle:REQ_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_POWER","kind":"Satisfy","source":"handle:BAT","target":"handle:REQ_POWER","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"VERIFY_START","kind":"Verify","source":"handle:TC_START","target":"handle:REQ_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"VERIFY_POWER","kind":"Verify","source":"handle:TC_POWER","target":"handle:REQ_POWER","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_LATENCY","kind":"DeriveRequirement","source":"handle:REQ_TRACE","target":"handle:REQ_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"TRACE_START","kind":"Trace","source":"handle:UC_START","target":"handle:REQ_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"ALLOC_START","kind":"Allocate","source":"handle:UC_START","target":"handle:CTRL","owner":"handle:PKG_BEHAVIOR"},
    {"op":"relationship","external_id":"UC_DRIVER","kind":"Association","source":"handle:DRIVER","target":"handle:UC_START","owner":"handle:PKG_UC","source_end":{"role_name":"driver","multiplicity":{"lower":1,"upper":1},"navigable":false,"aggregation":"None"},"target_end":{"role_name":"startVehicle","multiplicity":{"lower":1,"upper":1},"navigable":true,"aggregation":"None"}},
    {"op":"relationship","external_id":"UC_TECH","kind":"Association","source":"handle:TECH","target":"handle:UC_DIAG","owner":"handle:PKG_UC","source_end":{"role_name":"technician","multiplicity":{"lower":1,"upper":1},"navigable":false,"aggregation":"None"},"target_end":{"role_name":"diagnostics","multiplicity":{"lower":1,"upper":1},"navigable":true,"aggregation":"None"}},
    {"op":"relationship","external_id":"UC_INCLUDE","kind":"Include","source":"handle:UC_START","target":"handle:UC_DIAG","owner":"handle:PKG_UC"},
    {"op":"relationship","external_id":"PKG_IMPORT_COMMON","kind":"PackageImport","source":"handle:PKG_STRUCTURE","target":"handle:PKG_COMMON","owner":"handle:PKG_STRUCTURE","name":"reuse common definitions","visibility":"public"},
    {"op":"relationship","external_id":"PKG_DEP_BEHAVIOR_STRUCTURE","kind":"Dependency","source":"handle:PKG_BEHAVIOR","target":"handle:PKG_STRUCTURE","owner":"handle:PKG_BEHAVIOR","name":"behavior uses structure"},
    {"op":"relationship","external_id":"PKG_DEP_PARAM_STRUCTURE","kind":"Dependency","source":"handle:PKG_PARAM","target":"handle:PKG_STRUCTURE","owner":"handle:PKG_PARAM","name":"analysis constrains structure"},
    {"op":"connector","external_id":"CONN_BAT_MOTOR","context":"handle:VEH","kind":"Assembly","source_path":["P_BAT","BAT_POWER"],"target_path":["P_MOTOR","MOTOR_POWER"],"name":"tractionPower"},
    {"op":"connector","external_id":"CONN_CTRL_BAT","context":"handle:VEH","kind":"Assembly","source_path":["P_CTRL","CTRL_POWER"],"target_path":["P_BAT","BAT_POWER"],"name":"powerControl"},
    {"op":"item_flow","external_id":"FLOW_POWER","connector":"handle:CONN_BAT_MOTOR","source_path":["P_BAT","BAT_POWER"],"target_path":["P_MOTOR","MOTOR_POWER"],"conveyed_items":["handle:SIG_POWER_OK"],"name":"deliveredPower"},
    {"op":"activity","external_id":"ACT_PREFLIGHT","name":"PerformPreflightChecks","owner":"handle:PKG_ACTIVITIES","context":"handle:VEH"},
    {"op":"activity_node","external_id":"PF_INIT","activity":"handle:ACT_PREFLIGHT","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"PF_CHECK","activity":"handle:ACT_PREFLIGHT","name":"Check Preconditions","node":{"kind":"opaque_action","body":"true"}},
    {"op":"activity_node","external_id":"PF_FINAL","activity":"handle:ACT_PREFLIGHT","name":"Preflight Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"PF_E1","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_INIT","target":"handle:PF_CHECK"},
    {"op":"activity_edge","external_id":"PF_E2","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_CHECK","target":"handle:PF_FINAL"},
    {"op":"activity","external_id":"ACT_CTRL_OP","name":"InvokeControllerStartOperation","owner":"handle:PKG_ACTIVITIES","context":"handle:CTRL"},
    {"op":"activity_node","external_id":"CO_INIT","activity":"handle:ACT_CTRL_OP","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"CO_CALL","activity":"handle:ACT_CTRL_OP","name":"Invoke startVehicle","node":{"kind":"call_operation","operation":"handle:OP_START"}},
    {"op":"activity_node","external_id":"CO_FINAL","activity":"handle:ACT_CTRL_OP","name":"Operation Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"CO_E1","activity":"handle:ACT_CTRL_OP","name":"","kind":"ControlFlow","source":"handle:CO_INIT","target":"handle:CO_CALL"},
    {"op":"activity_edge","external_id":"CO_E2","activity":"handle:ACT_CTRL_OP","name":"","kind":"ControlFlow","source":"handle:CO_CALL","target":"handle:CO_FINAL"},
    {"op":"activity","external_id":"ACT_START","name":"StartVehicleBehavior","owner":"handle:PKG_ACTIVITIES","context":"handle:VEH"},
    {"op":"activity_partition","external_id":"PART_DRIVER","activity":"handle:ACT_START","name":"Driver","represented_element":"handle:DRIVER"},
    {"op":"activity_partition","external_id":"PART_CTRL","activity":"handle:ACT_START","name":"Controller","represented_element":"handle:CTRL"},
    {"op":"activity_node","external_id":"AN_INIT","activity":"handle:ACT_START","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"AN_PREFLIGHT","activity":"handle:ACT_START","name":"Perform Preflight Checks","node":{"kind":"call_behavior","activity":"handle:ACT_PREFLIGHT"},"partition":"handle:PART_DRIVER"},
    {"op":"activity_node","external_id":"AN_DECIDE","activity":"handle:ACT_START","name":"Startup Valid?","node":{"kind":"decision"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AN_SEND","activity":"handle:ACT_START","name":"Publish Vehicle Ready","node":{"kind":"send_signal","signal":"handle:SIG_READY"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AN_REJECT","activity":"handle:ACT_START","name":"Record Rejection","node":{"kind":"opaque_action","body":"false"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AN_FINAL","activity":"handle:ACT_START","name":"Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"AE1","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AN_INIT","target":"handle:AN_PREFLIGHT"},
    {"op":"activity_edge","external_id":"AE2","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AN_PREFLIGHT","target":"handle:AN_DECIDE"},
    {"op":"activity_edge","external_id":"AE3","activity":"handle:ACT_START","name":"valid","kind":"ControlFlow","source":"handle:AN_DECIDE","target":"handle:AN_SEND","guard":"true"},
    {"op":"activity_edge","external_id":"AE4","activity":"handle:ACT_START","name":"invalid","kind":"ControlFlow","source":"handle:AN_DECIDE","target":"handle:AN_REJECT","guard":"false"},
    {"op":"activity_edge","external_id":"AE5","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AN_SEND","target":"handle:AN_FINAL"},
    {"op":"activity_edge","external_id":"AE6","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AN_REJECT","target":"handle:AN_FINAL"},
    {"op":"state_machine","external_id":"SM","name":"VehicleOperatingStates","context":"handle:VEH"},
    {"op":"region","external_id":"SM_R","name":"Operating","state_machine":"handle:SM"},
    {"op":"vertex","external_id":"SV_INIT","region":"handle:SM_R","name":"Initial","vertex":{"kind":"pseudostate","pseudostate":"Initial"}},
    {"op":"vertex","external_id":"SV_OFF","region":"handle:SM_R","name":"Off","vertex":{"kind":"state","entry":"false"}},
    {"op":"vertex","external_id":"SV_READY","region":"handle:SM_R","name":"Ready","vertex":{"kind":"state","entry":"true"}},
    {"op":"vertex","external_id":"SV_FINAL","region":"handle:SM_R","name":"Complete","vertex":{"kind":"final_state"}},
    {"op":"transition","external_id":"ST1","region":"handle:SM_R","source":"handle:SV_INIT","target":"handle:SV_OFF"},
    {"op":"transition","external_id":"ST2","region":"handle:SM_R","source":"handle:SV_OFF","target":"handle:SV_READY","trigger":{"kind":"signal","signal":"handle:SIG_START"},"effect":"true"},
    {"op":"transition","external_id":"ST3","region":"handle:SM_R","source":"handle:SV_READY","target":"handle:SV_FINAL","trigger":{"kind":"signal","signal":"handle:SIG_STOP"},"effect":"true"},
    {"op":"interaction","external_id":"INT","name":"CommandedStartupSequence","context":"handle:VEH"},
    {"op":"lifeline","external_id":"LL_HMI","interaction":"handle:INT","name":"driverInterface","represented_path":["handle:P_HMI"]},
    {"op":"lifeline","external_id":"LL_CTRL","interaction":"handle:INT","name":"controller","represented_path":["handle:P_CTRL"]},
    {"op":"lifeline","external_id":"LL_BAT","interaction":"handle:INT","name":"battery","represented_path":["handle:P_BAT"]},
    {"op":"occurrence","external_id":"O1","interaction":"handle:INT","lifeline":"handle:LL_HMI","order":1},
    {"op":"occurrence","external_id":"O2","interaction":"handle:INT","lifeline":"handle:LL_CTRL","order":2},
    {"op":"occurrence","external_id":"O3","interaction":"handle:INT","lifeline":"handle:LL_CTRL","order":3},
    {"op":"occurrence","external_id":"O4","interaction":"handle:INT","lifeline":"handle:LL_BAT","order":4},
    {"op":"occurrence","external_id":"O5","interaction":"handle:INT","lifeline":"handle:LL_BAT","order":5},
    {"op":"occurrence","external_id":"O6","interaction":"handle:INT","lifeline":"handle:LL_CTRL","order":6},
    {"op":"occurrence","external_id":"O7","interaction":"handle:INT","lifeline":"handle:LL_CTRL","order":7},
    {"op":"occurrence","external_id":"O8","interaction":"handle:INT","lifeline":"handle:LL_HMI","order":8},
    {"op":"message","external_id":"M_START","interaction":"handle:INT","name":"startVehicle","sort":"SynchCall","send":"handle:O1","receive":"handle:O2","signature":{"kind":"operation","operation":"handle:OP_START"},"arguments":["1.0"]},
    {"op":"execution","external_id":"EX_START","interaction":"handle:INT","lifeline":"handle:LL_CTRL","start":"handle:O2","finish":"handle:O3","behavior":"handle:OP_START"},
    {"op":"message","external_id":"M_POWER","interaction":"handle:INT","name":"PowerEnable","sort":"AsynchSignal","send":"handle:O3","receive":"handle:O4","signature":{"kind":"signal","signal":"handle:SIG_POWER"}},
    {"op":"message","external_id":"M_POWER_OK","interaction":"handle:INT","name":"PowerAvailable","sort":"AsynchSignal","send":"handle:O5","receive":"handle:O6","signature":{"kind":"signal","signal":"handle:SIG_POWER_OK"}},
    {"op":"message","external_id":"M_READY","interaction":"handle:INT","name":"VehicleReady","sort":"AsynchSignal","send":"handle:O7","receive":"handle:O8","signature":{"kind":"signal","signal":"handle:SIG_READY"}},
    {"op":"state_invariant","external_id":"INV_READY","interaction":"handle:INT","lifeline":"handle:LL_CTRL","order":7,"constraint":"true"},
    {"op":"parametric_metadata","element":"handle:CB_FORCE","constraint_expression":"f = m * a"},
    {"op":"binding","external_id":"B_M","name":"massBinding","owner":"handle:VEH","source":{"role":"handle:V_MASS"},"target":{"role":"handle:C_FORCE","parameter":"handle:CP_M"}},
    {"op":"binding","external_id":"B_A","name":"accelerationBinding","owner":"handle:VEH","source":{"role":"handle:V_ACCEL"},"target":{"role":"handle:C_FORCE","parameter":"handle:CP_A"}},
    {"op":"binding","external_id":"B_F","name":"forceBinding","owner":"handle:VEH","source":{"role":"handle:V_FORCE"},"target":{"role":"handle:C_FORCE","parameter":"handle:CP_F"}}
  ],
  "diagrams": [
    {"external_id":"D_PKG","family":"Package","name":"Vehicle Model Organization","owner":"handle:PKG"},
    {"external_id":"D_COMMON_PKG","family":"Package","name":"Common Library Organization","owner":"handle:PKG_COMMON"},
    {"external_id":"D_SUBSYS_PKG","family":"Package","name":"Behavior Organization","owner":"handle:PKG_BEHAVIOR"},
    {"external_id":"D_BDD","family":"BDD","name":"Vehicle Definition and Component Hierarchy","owner":"handle:PKG_STRUCTURE"},
    {"external_id":"D_IBD","family":"IBD","name":"Electric Vehicle Internal Structure","owner":"handle:PKG_STRUCTURE","context":"handle:VEH"},
    {"external_id":"D_REQ","family":"Requirement","name":"Requirements and Verification Traceability","owner":"handle:PKG_REQ"},
    {"external_id":"D_UC","family":"Use Case","name":"Vehicle Use Cases","owner":"handle:PKG_UC","context":"handle:VEH"},
    {"external_id":"D_ACT","family":"Activity","name":"Commanded Startup Activity","owner":"handle:PKG_ACTIVITIES","semantic":"handle:ACT_START"},
    {"external_id":"D_ACT_PREFLIGHT","family":"Activity","name":"Preflight Checks","owner":"handle:PKG_ACTIVITIES","semantic":"handle:ACT_PREFLIGHT"},
    {"external_id":"D_ACT_CTRL_OP","family":"Activity","name":"Controller Operation Invocation","owner":"handle:PKG_ACTIVITIES","semantic":"handle:ACT_CTRL_OP"},
    {"external_id":"D_SM","family":"State Machine","name":"Vehicle Operating States","owner":"handle:PKG_STATES","semantic":"handle:SM"},
    {"external_id":"D_SEQ","family":"Sequence","name":"Commanded Startup Sequence","owner":"handle:PKG_INTERACTIONS","semantic":"handle:INT"},
    {"external_id":"D_PAR","family":"Parametric","name":"Vehicle Force Analysis","owner":"handle:PKG_PARAM","context":"handle:VEH"},
    {"external_id":"D_FLEET_BDD","family":"BDD","name":"Fleet Definition","owner":"handle:PKG_CONFIG"},
    {"external_id":"D_FLEET_IBD","family":"IBD","name":"Fleet Internal Structure","owner":"handle:PKG_CONFIG","context":"handle:FLEET"}
  ]
}
''')
