// Systems-Modeler-Pro PR57 professional SysML sales demonstration.
// Import this single .groovy file from File > Import Model Script.
// The bounded Groovy wrapper is parsed by the Rust model-script importer; it is not a backend-only fixture.
// The model intentionally stays compact while connecting requirements, architecture, interfaces,
// behavior, parametrics, verification, drill-down, and executable runtime demonstrations.
modelScript('''
{
  "source_namespace": "demo:professional-ev:v3",
  "operations": [
    {"op":"element","external_id":"PKG","kind":"Package","name":"Electric Vehicle Digital Engineering Demo","owner":"$root","documentation":"Professional connected SysML demonstration for requirements-driven architecture, behavior, analysis, verification, drill-down, and simulation."},
    {"op":"element","external_id":"PKG_COMMON","kind":"Package","name":"00 Common Library","owner":"handle:PKG"},
    {"op":"element","external_id":"PKG_TYPES","kind":"Package","name":"Types","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_IF","kind":"Package","name":"Interfaces","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_REQ","kind":"Package","name":"10 Requirements","owner":"handle:PKG","documentation":"Stakeholder, system, interface, and performance requirements."},
    {"op":"element","external_id":"PKG_VERIFY","kind":"Package","name":"Verification","owner":"handle:PKG_REQ","documentation":"Verification-facing requirement copies and TestCases."},
    {"op":"element","external_id":"PKG_UC","kind":"Package","name":"20 Operational Use Cases","owner":"handle:PKG"},
    {"op":"element","external_id":"PKG_ARCH","kind":"Package","name":"30 Architecture","owner":"handle:PKG","documentation":"Vehicle and subsystem definitions used by the executable runtime."},
    {"op":"element","external_id":"PKG_PT_TYPES","kind":"Package","name":"Powertrain Component Types","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_BEHAV","kind":"Package","name":"40 Behavior","owner":"handle:PKG"},
    {"op":"element","external_id":"PKG_ACT","kind":"Package","name":"Activities","owner":"handle:PKG_BEHAV"},
    {"op":"element","external_id":"PKG_STATE","kind":"Package","name":"State Machines","owner":"handle:PKG_BEHAV"},
    {"op":"element","external_id":"PKG_SEQ","kind":"Package","name":"Interactions","owner":"handle:PKG_BEHAV"},
    {"op":"element","external_id":"PKG_SIG","kind":"Package","name":"Signals","owner":"handle:PKG_BEHAV"},
    {"op":"element","external_id":"PKG_ANALYSIS","kind":"Package","name":"50 Analysis","owner":"handle:PKG","documentation":"Executable parametric sizing and performance analysis."},
    {"op":"element","external_id":"REAL","kind":"PrimitiveType","name":"Real","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"DATA_POWER","kind":"DataType","name":"PowerTransfer","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"DATA_COMMAND","kind":"DataType","name":"ControlCommand","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"DATA_BRAKE","kind":"DataType","name":"BrakeCommand","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"DATA_THERMAL","kind":"DataType","name":"ThermalCommand","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"DATA_SERVICE","kind":"DataType","name":"ServiceData","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"IF_POWER","kind":"InterfaceBlock","name":"PowerInterface","owner":"handle:PKG_IF"},
    {"op":"element","external_id":"IF_CONTROL","kind":"InterfaceBlock","name":"ControlInterface","owner":"handle:PKG_IF"},
    {"op":"element","external_id":"IF_BRAKE","kind":"InterfaceBlock","name":"BrakeInterface","owner":"handle:PKG_IF"},
    {"op":"element","external_id":"IF_THERMAL","kind":"InterfaceBlock","name":"ThermalInterface","owner":"handle:PKG_IF"},
    {"op":"element","external_id":"IF_SERVICE","kind":"InterfaceBlock","name":"ServiceInterface","owner":"handle:PKG_IF"},
    {"op":"element","external_id":"FP_POWER","kind":"FlowProperty","name":"power","owner":"handle:IF_POWER","type_ref":"handle:DATA_POWER","flow_direction":"Out"},
    {"op":"element","external_id":"FP_CONTROL","kind":"FlowProperty","name":"command","owner":"handle:IF_CONTROL","type_ref":"handle:DATA_COMMAND","flow_direction":"Out"},
    {"op":"element","external_id":"FP_BRAKE","kind":"FlowProperty","name":"brakeCommand","owner":"handle:IF_BRAKE","type_ref":"handle:DATA_BRAKE","flow_direction":"Out"},
    {"op":"element","external_id":"FP_THERMAL","kind":"FlowProperty","name":"thermalCommand","owner":"handle:IF_THERMAL","type_ref":"handle:DATA_THERMAL","flow_direction":"Out"},
    {"op":"element","external_id":"FP_SERVICE","kind":"FlowProperty","name":"serviceData","owner":"handle:IF_SERVICE","type_ref":"handle:DATA_SERVICE","flow_direction":"Out"},
    {"op":"element","external_id":"VEH","kind":"Block","name":"ElectricVehicle","owner":"handle:PKG_ARCH","documentation":"System-of-interest and common context for structural, behavioral, and parametric execution."},
    {"op":"element","external_id":"POWERTRAIN","kind":"Block","name":"Powertrain","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"BATTERY","kind":"Block","name":"BatterySystem","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"CTRL","kind":"Block","name":"VehicleController","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"HMI","kind":"Block","name":"HumanMachineInterface","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"BRAKES","kind":"Block","name":"BrakeSystem","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"THERMAL","kind":"Block","name":"ThermalManagement","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"INVERTER","kind":"Block","name":"TractionInverter","owner":"handle:PKG_PT_TYPES"},
    {"op":"element","external_id":"MOTOR","kind":"Block","name":"TractionMotor","owner":"handle:PKG_PT_TYPES"},
    {"op":"element","external_id":"P_POWERTRAIN","kind":"PartProperty","name":"powertrain","owner":"handle:VEH","type_ref":"handle:POWERTRAIN","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BATTERY","kind":"PartProperty","name":"batterySystem","owner":"handle:VEH","type_ref":"handle:BATTERY","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_CTRL","kind":"PartProperty","name":"controller","owner":"handle:VEH","type_ref":"handle:CTRL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_HMI","kind":"PartProperty","name":"hmi","owner":"handle:VEH","type_ref":"handle:HMI","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BRAKES","kind":"PartProperty","name":"brakes","owner":"handle:VEH","type_ref":"handle:BRAKES","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_THERMAL","kind":"PartProperty","name":"thermalManagement","owner":"handle:VEH","type_ref":"handle:THERMAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_INVERTER","kind":"PartProperty","name":"inverter","owner":"handle:POWERTRAIN","type_ref":"handle:INVERTER","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_MOTOR","kind":"PartProperty","name":"motor","owner":"handle:POWERTRAIN","type_ref":"handle:MOTOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"VEH_DRIVER","kind":"ProxyPort","name":"driverInput","owner":"handle:VEH","type_ref":"handle:IF_CONTROL"},
    {"op":"element","external_id":"VEH_SERVICE","kind":"FullPort","name":"service","owner":"handle:VEH","type_ref":"handle:IF_SERVICE"},
    {"op":"element","external_id":"HMI_CMD","kind":"ProxyPort","name":"driverCommand","owner":"handle:HMI","type_ref":"handle:IF_CONTROL"},
    {"op":"element","external_id":"CTRL_DRIVER","kind":"ProxyPort","name":"driverCommand","owner":"handle:CTRL","type_ref":"handle:IF_CONTROL","is_conjugated":true},
    {"op":"element","external_id":"CTRL_POWER_CMD","kind":"ProxyPort","name":"powerCommand","owner":"handle:CTRL","type_ref":"handle:IF_CONTROL"},
    {"op":"element","external_id":"CTRL_TORQUE","kind":"ProxyPort","name":"torqueCommand","owner":"handle:CTRL","type_ref":"handle:IF_CONTROL"},
    {"op":"element","external_id":"CTRL_BRAKE","kind":"ProxyPort","name":"brakeCommand","owner":"handle:CTRL","type_ref":"handle:IF_BRAKE"},
    {"op":"element","external_id":"CTRL_THERM","kind":"ProxyPort","name":"thermalCommand","owner":"handle:CTRL","type_ref":"handle:IF_THERMAL"},
    {"op":"element","external_id":"CTRL_SERVICE","kind":"FullPort","name":"service","owner":"handle:CTRL","type_ref":"handle:IF_SERVICE","is_conjugated":true},
    {"op":"element","external_id":"BAT_CMD","kind":"ProxyPort","name":"powerCommand","owner":"handle:BATTERY","type_ref":"handle:IF_CONTROL","is_conjugated":true},
    {"op":"element","external_id":"BAT_POWER","kind":"ProxyPort","name":"powerOut","owner":"handle:BATTERY","type_ref":"handle:IF_POWER"},
    {"op":"element","external_id":"PT_POWER","kind":"ProxyPort","name":"powerIn","owner":"handle:POWERTRAIN","type_ref":"handle:IF_POWER","is_conjugated":true},
    {"op":"element","external_id":"PT_TORQUE","kind":"ProxyPort","name":"torqueCommand","owner":"handle:POWERTRAIN","type_ref":"handle:IF_CONTROL","is_conjugated":true},
    {"op":"element","external_id":"BRAKE_CMD","kind":"ProxyPort","name":"brakeCommand","owner":"handle:BRAKES","type_ref":"handle:IF_BRAKE","is_conjugated":true},
    {"op":"element","external_id":"THERM_CMD","kind":"ProxyPort","name":"thermalCommand","owner":"handle:THERMAL","type_ref":"handle:IF_THERMAL","is_conjugated":true},
    {"op":"element","external_id":"INV_POWER_IN","kind":"ProxyPort","name":"powerIn","owner":"handle:INVERTER","type_ref":"handle:IF_POWER","is_conjugated":true},
    {"op":"element","external_id":"INV_POWER_OUT","kind":"ProxyPort","name":"powerOut","owner":"handle:INVERTER","type_ref":"handle:IF_POWER"},
    {"op":"element","external_id":"INV_TORQUE","kind":"ProxyPort","name":"torqueCommand","owner":"handle:INVERTER","type_ref":"handle:IF_CONTROL","is_conjugated":true},
    {"op":"element","external_id":"MOTOR_POWER","kind":"ProxyPort","name":"powerIn","owner":"handle:MOTOR","type_ref":"handle:IF_POWER","is_conjugated":true},
    {"op":"element","external_id":"OP_START","kind":"Operation","name":"startVehicle","owner":"handle:CTRL"},
    {"op":"element","external_id":"OP_TORQUE","kind":"Operation","name":"requestTorque","owner":"handle:CTRL"},
    {"op":"element","external_id":"PAR_TORQUE","kind":"Parameter","name":"torqueRequest","owner":"handle:OP_TORQUE","type_ref":"handle:REAL","parameter_direction":"In","default_value":"1.0","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"OP_STOP","kind":"Operation","name":"stopVehicle","owner":"handle:CTRL"},
    {"op":"element","external_id":"SIG_START","kind":"Signal","name":"StartCommand","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_POWER_ENABLE","kind":"Signal","name":"PowerEnable","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_POWER_AVAILABLE","kind":"Signal","name":"PowerAvailable","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_READY","kind":"Signal","name":"VehicleReady","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_TORQUE","kind":"Signal","name":"TorqueCommand","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_STOP","kind":"Signal","name":"StopCommand","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"SIG_FAULT","kind":"Signal","name":"FaultDetected","owner":"handle:PKG_SIG"},
    {"op":"element","external_id":"REC_START","kind":"Reception","name":"startCommand","owner":"handle:CTRL","type_ref":"handle:SIG_START"},
    {"op":"element","external_id":"REC_POWER_AVAILABLE","kind":"Reception","name":"powerAvailable","owner":"handle:CTRL","type_ref":"handle:SIG_POWER_AVAILABLE"},
    {"op":"element","external_id":"REC_FAULT","kind":"Reception","name":"faultDetected","owner":"handle:CTRL","type_ref":"handle:SIG_FAULT"},
    {"op":"element","external_id":"REC_POWER_ENABLE","kind":"Reception","name":"powerEnable","owner":"handle:BATTERY","type_ref":"handle:SIG_POWER_ENABLE"},
    {"op":"element","external_id":"REC_TORQUE","kind":"Reception","name":"torqueCommand","owner":"handle:POWERTRAIN","type_ref":"handle:SIG_TORQUE"},
    {"op":"element","external_id":"R_SAFE","kind":"Requirement","name":"SafeControlledOperation","owner":"handle:PKG_REQ","requirement_id":"STK-001","requirement_text":"The electric vehicle shall provide safe, controlled operation for the driver across normal and detected-fault conditions."},
    {"op":"element","external_id":"R_RANGE","kind":"Requirement","name":"DrivingRange","owner":"handle:PKG_REQ","requirement_id":"STK-002","requirement_text":"The electric vehicle shall provide at least 400 km of nominal driving range."},
    {"op":"element","external_id":"R_PERF","kind":"Requirement","name":"ResponsivePerformance","owner":"handle:PKG_REQ","requirement_id":"STK-003","requirement_text":"The electric vehicle shall provide responsive commanded propulsion performance."},
    {"op":"element","external_id":"R_START","kind":"Requirement","name":"CommandedStartup","owner":"handle:PKG_REQ","requirement_id":"SYS-001","requirement_text":"The vehicle shall transition from Off to Ready after a valid start command and successful preflight checks."},
    {"op":"element","external_id":"R_PROP","kind":"Requirement","name":"PropulsionDelivery","owner":"handle:PKG_REQ","requirement_id":"SYS-002","requirement_text":"The powertrain shall deliver commanded traction power through the modeled control and power interfaces."},
    {"op":"element","external_id":"R_ENERGY","kind":"Requirement","name":"EnergyStorage","owner":"handle:PKG_REQ","requirement_id":"SYS-003","requirement_text":"The battery system shall provide stored electrical energy sufficient to support the allocated driving-range requirement."},
    {"op":"element","external_id":"R_BRAKE","kind":"Requirement","name":"CommandedBraking","owner":"handle:PKG_REQ","requirement_id":"SYS-004","requirement_text":"The brake system shall respond to commanded braking and support safe controlled operation."},
    {"op":"element","external_id":"R_THERM","kind":"Requirement","name":"ThermalControl","owner":"handle:PKG_REQ","requirement_id":"SYS-005","requirement_text":"The thermal management system shall respond to thermal-control commands during vehicle operation."},
    {"op":"element","external_id":"R_INTERFACE","kind":"Requirement","name":"TypedInterfaces","owner":"handle:PKG_REQ","requirement_id":"IF-001","requirement_text":"Subsystem interactions shall use explicitly typed SysML ports, connectors, and conveyed items."},
    {"op":"element","external_id":"R_FORCE","kind":"Requirement","name":"TractiveForce","owner":"handle:PKG_REQ","requirement_id":"PERF-001","requirement_text":"At the demonstration operating point, the vehicle shall provide at least 4500 N of tractive force."},
    {"op":"element","external_id":"R_POWER","kind":"Requirement","name":"ElectricalPower","owner":"handle:PKG_REQ","requirement_id":"PERF-002","requirement_text":"At the demonstration operating point, the propulsion system shall support 135 kW of electrical power."},
    {"op":"element","external_id":"RV_START","kind":"Requirement","name":"Verify Commanded Startup","owner":"handle:PKG_VERIFY","requirement_id":"VER-001","requirement_text":"Verification copy of the commanded-startup requirement."},
    {"op":"element","external_id":"RV_RANGE","kind":"Requirement","name":"Verify Driving Range","owner":"handle:PKG_VERIFY","requirement_id":"VER-002","requirement_text":"Verification copy of the driving-range requirement."},
    {"op":"element","external_id":"RV_FORCE","kind":"Requirement","name":"Verify Tractive Force","owner":"handle:PKG_VERIFY","requirement_id":"VER-003","requirement_text":"Verification copy of the tractive-force requirement."},
    {"op":"element","external_id":"RV_POWER","kind":"Requirement","name":"Verify Electrical Power","owner":"handle:PKG_VERIFY","requirement_id":"VER-004","requirement_text":"Verification copy of the electrical-power requirement."},
    {"op":"element","external_id":"RV_BRAKE","kind":"Requirement","name":"Verify Commanded Braking","owner":"handle:PKG_VERIFY","requirement_id":"VER-005","requirement_text":"Verification copy of the commanded-braking requirement."},
    {"op":"element","external_id":"TC_START","kind":"TestCase","name":"StartupScenarioTest","owner":"handle:PKG_VERIFY"},
    {"op":"element","external_id":"TC_RANGE","kind":"TestCase","name":"RangeAnalysisTest","owner":"handle:PKG_VERIFY"},
    {"op":"element","external_id":"TC_FORCE","kind":"TestCase","name":"TractiveForceAnalysisTest","owner":"handle:PKG_VERIFY"},
    {"op":"element","external_id":"TC_POWER","kind":"TestCase","name":"ElectricalPowerAnalysisTest","owner":"handle:PKG_VERIFY"},
    {"op":"element","external_id":"TC_BRAKE","kind":"TestCase","name":"BrakeCommandTest","owner":"handle:PKG_VERIFY"},
    {"op":"element","external_id":"DRIVER","kind":"Actor","name":"Driver","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"TECH","kind":"Actor","name":"ServiceTechnician","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"UC_OPERATE","kind":"UseCase","name":"OperateVehicle","owner":"handle:PKG_UC","extension_points":["fault handling"]},
    {"op":"element","external_id":"UC_START","kind":"UseCase","name":"StartVehicle","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"UC_DRIVE","kind":"UseCase","name":"DriveVehicle","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"UC_SERVICE","kind":"UseCase","name":"ServiceVehicle","owner":"handle:PKG_UC"},
    {"op":"element","external_id":"V_MASS","kind":"ValueProperty","name":"mass","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"1800","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_ACCEL","kind":"ValueProperty","name":"acceleration","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"2.5","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_FORCE","kind":"ValueProperty","name":"tractiveForce","owner":"handle:VEH","type_ref":"handle:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_SPEED","kind":"ValueProperty","name":"targetSpeed","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"30","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_POWER","kind":"ValueProperty","name":"electricalPower","owner":"handle:VEH","type_ref":"handle:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_ENERGY","kind":"ValueProperty","name":"batteryEnergy","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"80","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_CONSUMPTION","kind":"ValueProperty","name":"energyConsumption","owner":"handle:VEH","type_ref":"handle:REAL","default_value":"0.2","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"V_RANGE","kind":"ValueProperty","name":"estimatedRange","owner":"handle:VEH","type_ref":"handle:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"CB_FORCE","kind":"ConstraintBlock","name":"TractiveForceEquation","owner":"handle:PKG_ANALYSIS"},
    {"op":"element","external_id":"CF_M","kind":"ConstraintParameter","name":"m","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CF_A","kind":"ConstraintParameter","name":"a","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CF_F","kind":"ConstraintParameter","name":"F","owner":"handle:CB_FORCE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"C_FORCE","kind":"ConstraintProperty","name":"tractiveForceAnalysis","owner":"handle:VEH","type_ref":"handle:CB_FORCE","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"CB_POWER","kind":"ConstraintBlock","name":"ElectricalPowerEquation","owner":"handle:PKG_ANALYSIS"},
    {"op":"element","external_id":"CP_F","kind":"ConstraintParameter","name":"F","owner":"handle:CB_POWER","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CP_V","kind":"ConstraintParameter","name":"v","owner":"handle:CB_POWER","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CP_P","kind":"ConstraintParameter","name":"P","owner":"handle:CB_POWER","type_ref":"handle:REAL"},
    {"op":"element","external_id":"C_POWER","kind":"ConstraintProperty","name":"electricalPowerAnalysis","owner":"handle:VEH","type_ref":"handle:CB_POWER","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"CB_RANGE","kind":"ConstraintBlock","name":"RangeEquation","owner":"handle:PKG_ANALYSIS"},
    {"op":"element","external_id":"CR_E","kind":"ConstraintParameter","name":"E","owner":"handle:CB_RANGE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CR_C","kind":"ConstraintParameter","name":"c","owner":"handle:CB_RANGE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"CR_R","kind":"ConstraintParameter","name":"R","owner":"handle:CB_RANGE","type_ref":"handle:REAL"},
    {"op":"element","external_id":"C_RANGE","kind":"ConstraintProperty","name":"rangeAnalysis","owner":"handle:VEH","type_ref":"handle:CB_RANGE","multiplicity":{"lower":1,"upper":1}},
    {"op":"relationship","external_id":"PKG_IMPORT_COMMON","kind":"PackageImport","source":"handle:PKG_ARCH","target":"handle:PKG_COMMON","owner":"handle:PKG_ARCH","name":"reuse common definitions","visibility":"public"},
    {"op":"relationship","external_id":"PKG_DEP_BEHAV_ARCH","kind":"Dependency","source":"handle:PKG_BEHAV","target":"handle:PKG_ARCH","owner":"handle:PKG_BEHAV","name":"behavior executes architecture"},
    {"op":"relationship","external_id":"PKG_DEP_ANALYSIS_ARCH","kind":"Dependency","source":"handle:PKG_ANALYSIS","target":"handle:PKG_ARCH","owner":"handle:PKG_ANALYSIS","name":"analysis evaluates vehicle properties"},
    {"op":"relationship","external_id":"PKG_DEP_UC_REQ","kind":"Dependency","source":"handle:PKG_UC","target":"handle:PKG_REQ","owner":"handle:PKG_UC","name":"operations trace to requirements"},
    {"op":"relationship","external_id":"DERIVE_START","kind":"DeriveRequirement","source":"handle:R_START","target":"handle:R_SAFE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_BRAKE","kind":"DeriveRequirement","source":"handle:R_BRAKE","target":"handle:R_SAFE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_THERM","kind":"DeriveRequirement","source":"handle:R_THERM","target":"handle:R_SAFE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_PROP","kind":"DeriveRequirement","source":"handle:R_PROP","target":"handle:R_PERF","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_ENERGY","kind":"DeriveRequirement","source":"handle:R_ENERGY","target":"handle:R_RANGE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_FORCE","kind":"DeriveRequirement","source":"handle:R_FORCE","target":"handle:R_PROP","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_POWER","kind":"DeriveRequirement","source":"handle:R_POWER","target":"handle:R_PROP","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"DERIVE_INTERFACE","kind":"DeriveRequirement","source":"handle:R_INTERFACE","target":"handle:R_PROP","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_SAFE","kind":"Satisfy","source":"handle:VEH","target":"handle:R_SAFE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_START","kind":"Satisfy","source":"handle:CTRL","target":"handle:R_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_PROP","kind":"Satisfy","source":"handle:POWERTRAIN","target":"handle:R_PROP","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_ENERGY","kind":"Satisfy","source":"handle:BATTERY","target":"handle:R_ENERGY","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_BRAKE","kind":"Satisfy","source":"handle:BRAKES","target":"handle:R_BRAKE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_THERM","kind":"Satisfy","source":"handle:THERMAL","target":"handle:R_THERM","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"SAT_INTERFACE","kind":"Satisfy","source":"handle:CTRL","target":"handle:R_INTERFACE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"REF_FORCE","kind":"Refine","source":"handle:CB_FORCE","target":"handle:R_FORCE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"REF_POWER","kind":"Refine","source":"handle:CB_POWER","target":"handle:R_POWER","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"REF_RANGE","kind":"Refine","source":"handle:CB_RANGE","target":"handle:R_RANGE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"COPY_START","kind":"Copy","source":"handle:RV_START","target":"handle:R_START","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"COPY_RANGE","kind":"Copy","source":"handle:RV_RANGE","target":"handle:R_RANGE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"COPY_FORCE","kind":"Copy","source":"handle:RV_FORCE","target":"handle:R_FORCE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"COPY_POWER","kind":"Copy","source":"handle:RV_POWER","target":"handle:R_POWER","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"COPY_BRAKE","kind":"Copy","source":"handle:RV_BRAKE","target":"handle:R_BRAKE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"VERIFY_START","kind":"Verify","source":"handle:TC_START","target":"handle:RV_START","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"VERIFY_RANGE","kind":"Verify","source":"handle:TC_RANGE","target":"handle:RV_RANGE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"VERIFY_FORCE","kind":"Verify","source":"handle:TC_FORCE","target":"handle:RV_FORCE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"VERIFY_POWER","kind":"Verify","source":"handle:TC_POWER","target":"handle:RV_POWER","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"VERIFY_BRAKE","kind":"Verify","source":"handle:TC_BRAKE","target":"handle:RV_BRAKE","owner":"handle:PKG_VERIFY"},
    {"op":"relationship","external_id":"UC_DRIVER_OPERATE","kind":"Association","source":"handle:DRIVER","target":"handle:UC_OPERATE","owner":"handle:PKG_UC","source_end":{"role_name":"driver","multiplicity":{"lower":1,"upper":1},"navigable":false,"aggregation":"None"},"target_end":{"role_name":"operateVehicle","multiplicity":{"lower":1,"upper":1},"navigable":true,"aggregation":"None"}},
    {"op":"relationship","external_id":"UC_TECH_SERVICE","kind":"Association","source":"handle:TECH","target":"handle:UC_SERVICE","owner":"handle:PKG_UC","source_end":{"role_name":"technician","multiplicity":{"lower":1,"upper":1},"navigable":false,"aggregation":"None"},"target_end":{"role_name":"serviceVehicle","multiplicity":{"lower":1,"upper":1},"navigable":true,"aggregation":"None"}},
    {"op":"relationship","external_id":"UC_INCLUDE_START","kind":"Include","source":"handle:UC_OPERATE","target":"handle:UC_START","owner":"handle:PKG_UC"},
    {"op":"relationship","external_id":"UC_DRIVE_GENERAL","kind":"Generalization","source":"handle:UC_DRIVE","target":"handle:UC_OPERATE","owner":"handle:PKG_UC"},
    {"op":"relationship","external_id":"UC_SERVICE_EXTEND","kind":"Extend","source":"handle:UC_SERVICE","target":"handle:UC_OPERATE","owner":"handle:PKG_UC","extension_condition":"fault detected","extension_location":"fault handling"},
    {"op":"relationship","external_id":"TRACE_UC_START","kind":"Trace","source":"handle:UC_START","target":"handle:R_START","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"TRACE_UC_DRIVE","kind":"Trace","source":"handle:UC_DRIVE","target":"handle:R_PROP","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"TRACE_UC_SERVICE","kind":"Trace","source":"handle:UC_SERVICE","target":"handle:R_SAFE","owner":"handle:PKG_REQ"},
    {"op":"relationship","external_id":"ALLOC_DRIVE","kind":"Allocate","source":"handle:UC_DRIVE","target":"handle:CTRL","owner":"handle:PKG_BEHAV"},
    {"op":"connector","external_id":"CONN_HMI_CTRL","context":"handle:VEH","kind":"Assembly","source_path":["P_HMI","HMI_CMD"],"target_path":["P_CTRL","CTRL_DRIVER"],"name":"driverCommands"},
    {"op":"connector","external_id":"CONN_CTRL_BAT","context":"handle:VEH","kind":"Assembly","source_path":["P_CTRL","CTRL_POWER_CMD"],"target_path":["P_BATTERY","BAT_CMD"],"name":"powerControl"},
    {"op":"connector","external_id":"CONN_BAT_PT","context":"handle:VEH","kind":"Assembly","source_path":["P_BATTERY","BAT_POWER"],"target_path":["P_POWERTRAIN","PT_POWER"],"name":"tractionPower"},
    {"op":"connector","external_id":"CONN_CTRL_PT","context":"handle:VEH","kind":"Assembly","source_path":["P_CTRL","CTRL_TORQUE"],"target_path":["P_POWERTRAIN","PT_TORQUE"],"name":"torqueCommand"},
    {"op":"connector","external_id":"CONN_CTRL_BRAKE","context":"handle:VEH","kind":"Assembly","source_path":["P_CTRL","CTRL_BRAKE"],"target_path":["P_BRAKES","BRAKE_CMD"],"name":"brakeCommand"},
    {"op":"connector","external_id":"CONN_CTRL_THERM","context":"handle:VEH","kind":"Assembly","source_path":["P_CTRL","CTRL_THERM"],"target_path":["P_THERMAL","THERM_CMD"],"name":"thermalCommand"},
    {"op":"connector","external_id":"CONN_DRIVER_DELEG","context":"handle:VEH","kind":"Delegation","source_path":["VEH_DRIVER"],"target_path":["P_HMI","HMI_CMD"],"name":"driverInputDelegation"},
    {"op":"connector","external_id":"CONN_SERVICE_DELEG","context":"handle:VEH","kind":"Delegation","source_path":["VEH_SERVICE"],"target_path":["P_CTRL","CTRL_SERVICE"],"name":"serviceDelegation"},
    {"op":"item_flow","external_id":"FLOW_HMI_CTRL","connector":"handle:CONN_HMI_CTRL","source_path":["P_HMI","HMI_CMD"],"target_path":["P_CTRL","CTRL_DRIVER"],"conveyed_items":["handle:DATA_COMMAND"],"name":"driverCommand"},
    {"op":"item_flow","external_id":"FLOW_CTRL_BAT","connector":"handle:CONN_CTRL_BAT","source_path":["P_CTRL","CTRL_POWER_CMD"],"target_path":["P_BATTERY","BAT_CMD"],"conveyed_items":["handle:DATA_COMMAND"],"name":"powerCommand"},
    {"op":"item_flow","external_id":"FLOW_BAT_PT","connector":"handle:CONN_BAT_PT","source_path":["P_BATTERY","BAT_POWER"],"target_path":["P_POWERTRAIN","PT_POWER"],"conveyed_items":["handle:DATA_POWER"],"name":"tractionPower"},
    {"op":"item_flow","external_id":"FLOW_CTRL_PT","connector":"handle:CONN_CTRL_PT","source_path":["P_CTRL","CTRL_TORQUE"],"target_path":["P_POWERTRAIN","PT_TORQUE"],"conveyed_items":["handle:DATA_COMMAND"],"name":"torqueCommand"},
    {"op":"item_flow","external_id":"FLOW_CTRL_BRAKE","connector":"handle:CONN_CTRL_BRAKE","source_path":["P_CTRL","CTRL_BRAKE"],"target_path":["P_BRAKES","BRAKE_CMD"],"conveyed_items":["handle:DATA_BRAKE"],"name":"brakeCommand"},
    {"op":"item_flow","external_id":"FLOW_CTRL_THERM","connector":"handle:CONN_CTRL_THERM","source_path":["P_CTRL","CTRL_THERM"],"target_path":["P_THERMAL","THERM_CMD"],"conveyed_items":["handle:DATA_THERMAL"],"name":"thermalCommand"},
    {"op":"item_flow","external_id":"FLOW_DRIVER_DELEG","connector":"handle:CONN_DRIVER_DELEG","source_path":["VEH_DRIVER"],"target_path":["P_HMI","HMI_CMD"],"conveyed_items":["handle:DATA_COMMAND"],"name":"driverInput"},
    {"op":"item_flow","external_id":"FLOW_SERVICE_DELEG","connector":"handle:CONN_SERVICE_DELEG","source_path":["VEH_SERVICE"],"target_path":["P_CTRL","CTRL_SERVICE"],"conveyed_items":["handle:DATA_SERVICE"],"name":"serviceData"},
    {"op":"connector","external_id":"CONN_PT_INV_POWER","context":"handle:POWERTRAIN","kind":"Delegation","source_path":["PT_POWER"],"target_path":["P_INVERTER","INV_POWER_IN"],"name":"powerDelegation"},
    {"op":"connector","external_id":"CONN_PT_INV_TORQUE","context":"handle:POWERTRAIN","kind":"Delegation","source_path":["PT_TORQUE"],"target_path":["P_INVERTER","INV_TORQUE"],"name":"torqueDelegation"},
    {"op":"connector","external_id":"CONN_INV_MOTOR","context":"handle:POWERTRAIN","kind":"Assembly","source_path":["P_INVERTER","INV_POWER_OUT"],"target_path":["P_MOTOR","MOTOR_POWER"],"name":"motorPower"},
    {"op":"item_flow","external_id":"FLOW_PT_INV_POWER","connector":"handle:CONN_PT_INV_POWER","source_path":["PT_POWER"],"target_path":["P_INVERTER","INV_POWER_IN"],"conveyed_items":["handle:DATA_POWER"],"name":"inputPower"},
    {"op":"item_flow","external_id":"FLOW_PT_INV_TORQUE","connector":"handle:CONN_PT_INV_TORQUE","source_path":["PT_TORQUE"],"target_path":["P_INVERTER","INV_TORQUE"],"conveyed_items":["handle:DATA_COMMAND"],"name":"torqueRequest"},
    {"op":"item_flow","external_id":"FLOW_INV_MOTOR","connector":"handle:CONN_INV_MOTOR","source_path":["P_INVERTER","INV_POWER_OUT"],"target_path":["P_MOTOR","MOTOR_POWER"],"conveyed_items":["handle:DATA_POWER"],"name":"motorPower"},
    {"op":"activity","external_id":"ACT_START","name":"StartVehicle","owner":"handle:PKG_ACT","context":"handle:VEH"},
    {"op":"activity_partition","external_id":"PART_DRIVER","activity":"handle:ACT_START","name":"Driver","represented_element":"handle:DRIVER"},
    {"op":"activity_partition","external_id":"PART_CTRL","activity":"handle:ACT_START","name":"Vehicle Controller","represented_element":"handle:CTRL"},
    {"op":"activity_node","external_id":"AS_INIT","activity":"handle:ACT_START","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"AS_PREFLIGHT","activity":"handle:ACT_START","name":"Check Preconditions","node":{"kind":"opaque_action","body":"true"},"partition":"handle:PART_DRIVER"},
    {"op":"activity_node","external_id":"AS_CALL","activity":"handle:ACT_START","name":"Invoke startVehicle","node":{"kind":"call_operation","operation":"handle:OP_START"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AS_POWER","activity":"handle:ACT_START","name":"Enable Battery Power","node":{"kind":"send_signal","signal":"handle:SIG_POWER_ENABLE"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AS_WAIT","activity":"handle:ACT_START","name":"Await Power Available","node":{"kind":"accept_event","signal":"handle:SIG_POWER_AVAILABLE"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AS_READY","activity":"handle:ACT_START","name":"Publish Vehicle Ready","node":{"kind":"send_signal","signal":"handle:SIG_READY"},"partition":"handle:PART_CTRL"},
    {"op":"activity_node","external_id":"AS_FINAL","activity":"handle:ACT_START","name":"Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"AS_E1","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_INIT","target":"handle:AS_PREFLIGHT"},
    {"op":"activity_edge","external_id":"AS_E2","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_PREFLIGHT","target":"handle:AS_CALL"},
    {"op":"activity_edge","external_id":"AS_E3","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_CALL","target":"handle:AS_POWER"},
    {"op":"activity_edge","external_id":"AS_E4","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_POWER","target":"handle:AS_WAIT"},
    {"op":"activity_edge","external_id":"AS_E5","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_WAIT","target":"handle:AS_READY"},
    {"op":"activity_edge","external_id":"AS_E6","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:AS_READY","target":"handle:AS_FINAL"},
    {"op":"activity","external_id":"ACT_OPERATE","name":"OperateElectricVehicle","owner":"handle:PKG_ACT","context":"handle:VEH"},
    {"op":"activity_partition","external_id":"PART_OPER_DRIVER","activity":"handle:ACT_OPERATE","name":"Driver","represented_element":"handle:DRIVER"},
    {"op":"activity_partition","external_id":"PART_OPER_CTRL","activity":"handle:ACT_OPERATE","name":"Vehicle Controller","represented_element":"handle:CTRL"},
    {"op":"activity_node","external_id":"AO_INIT","activity":"handle:ACT_OPERATE","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"AO_START","activity":"handle:ACT_OPERATE","name":"Start Vehicle","node":{"kind":"call_behavior","activity":"handle:ACT_START"},"partition":"handle:PART_OPER_DRIVER"},
    {"op":"activity_node","external_id":"AO_TORQUE","activity":"handle:ACT_OPERATE","name":"Request Propulsion Torque","node":{"kind":"call_operation","operation":"handle:OP_TORQUE"},"partition":"handle:PART_OPER_CTRL"},
    {"op":"activity_node","external_id":"AO_SIGNAL","activity":"handle:ACT_OPERATE","name":"Publish Torque Command","node":{"kind":"send_signal","signal":"handle:SIG_TORQUE"},"partition":"handle:PART_OPER_CTRL"},
    {"op":"activity_node","external_id":"AO_STOP","activity":"handle:ACT_OPERATE","name":"Stop Vehicle","node":{"kind":"call_operation","operation":"handle:OP_STOP"},"partition":"handle:PART_OPER_CTRL"},
    {"op":"activity_node","external_id":"AO_FINAL","activity":"handle:ACT_OPERATE","name":"Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"AO_E1","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:AO_INIT","target":"handle:AO_START"},
    {"op":"activity_edge","external_id":"AO_E2","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:AO_START","target":"handle:AO_TORQUE"},
    {"op":"activity_edge","external_id":"AO_E3","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:AO_TORQUE","target":"handle:AO_SIGNAL"},
    {"op":"activity_edge","external_id":"AO_E4","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:AO_SIGNAL","target":"handle:AO_STOP"},
    {"op":"activity_edge","external_id":"AO_E5","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:AO_STOP","target":"handle:AO_FINAL"},
    {"op":"state_machine","external_id":"SM_VEH","name":"VehicleOperatingModes","context":"handle:VEH"},
    {"op":"region","external_id":"SM_REGION","name":"Operating Modes","state_machine":"handle:SM_VEH"},
    {"op":"vertex","external_id":"SV_INIT","region":"handle:SM_REGION","name":"Initial","vertex":{"kind":"pseudostate","pseudostate":"Initial"}},
    {"op":"vertex","external_id":"SV_OFF","region":"handle:SM_REGION","name":"Off","vertex":{"kind":"state","entry":"false"}},
    {"op":"vertex","external_id":"SV_READY","region":"handle:SM_REGION","name":"Ready","vertex":{"kind":"state","entry":"true"}},
    {"op":"vertex","external_id":"SV_DRIVING","region":"handle:SM_REGION","name":"Driving","vertex":{"kind":"state","do_activity":"true"}},
    {"op":"vertex","external_id":"SV_FAULT","region":"handle:SM_REGION","name":"Fault","vertex":{"kind":"state","entry":"true"}},
    {"op":"transition","external_id":"SM_T0","region":"handle:SM_REGION","source":"handle:SV_INIT","target":"handle:SV_OFF"},
    {"op":"transition","external_id":"SM_T1","region":"handle:SM_REGION","source":"handle:SV_OFF","target":"handle:SV_READY","trigger":{"kind":"signal","signal":"handle:SIG_START"},"effect":"true"},
    {"op":"transition","external_id":"SM_T2","region":"handle:SM_REGION","source":"handle:SV_READY","target":"handle:SV_DRIVING","trigger":{"kind":"signal","signal":"handle:SIG_TORQUE"},"effect":"true"},
    {"op":"transition","external_id":"SM_T3","region":"handle:SM_REGION","source":"handle:SV_DRIVING","target":"handle:SV_OFF","trigger":{"kind":"signal","signal":"handle:SIG_STOP"},"effect":"true"},
    {"op":"transition","external_id":"SM_T4","region":"handle:SM_REGION","source":"handle:SV_READY","target":"handle:SV_FAULT","trigger":{"kind":"signal","signal":"handle:SIG_FAULT"},"effect":"true"},
    {"op":"transition","external_id":"SM_T5","region":"handle:SM_REGION","source":"handle:SV_DRIVING","target":"handle:SV_FAULT","trigger":{"kind":"signal","signal":"handle:SIG_FAULT"},"effect":"true"},
    {"op":"interaction","external_id":"INT_STARTUP","name":"VehicleStartupSequence","context":"handle:VEH"},
    {"op":"lifeline","external_id":"LL_HMI","interaction":"handle:INT_STARTUP","name":"hmi","represented_path":["handle:P_HMI"]},
    {"op":"lifeline","external_id":"LL_CTRL","interaction":"handle:INT_STARTUP","name":"controller","represented_path":["handle:P_CTRL"]},
    {"op":"lifeline","external_id":"LL_BAT","interaction":"handle:INT_STARTUP","name":"batterySystem","represented_path":["handle:P_BATTERY"]},
    {"op":"lifeline","external_id":"LL_INV","interaction":"handle:INT_STARTUP","name":"inverter","represented_path":["handle:P_POWERTRAIN","handle:P_INVERTER"]},
    {"op":"occurrence","external_id":"O1","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_HMI","order":1},
    {"op":"occurrence","external_id":"O2","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","order":2},
    {"op":"occurrence","external_id":"O3","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","order":3},
    {"op":"occurrence","external_id":"O4","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_BAT","order":4},
    {"op":"occurrence","external_id":"O5","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_BAT","order":5},
    {"op":"occurrence","external_id":"O6","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","order":6},
    {"op":"occurrence","external_id":"O7","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","order":7},
    {"op":"occurrence","external_id":"O8","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_INV","order":8},
    {"op":"occurrence","external_id":"O9","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","order":9},
    {"op":"occurrence","external_id":"O10","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_HMI","order":10},
    {"op":"message","external_id":"M_START","interaction":"handle:INT_STARTUP","name":"startVehicle","sort":"SynchCall","send":"handle:O1","receive":"handle:O2","signature":{"kind":"operation","operation":"handle:OP_START"}},
    {"op":"execution","external_id":"EX_START","interaction":"handle:INT_STARTUP","lifeline":"handle:LL_CTRL","start":"handle:O2","finish":"handle:O3","behavior":"handle:OP_START"},
    {"op":"message","external_id":"M_POWER_ENABLE","interaction":"handle:INT_STARTUP","name":"PowerEnable","sort":"AsynchSignal","send":"handle:O3","receive":"handle:O4","signature":{"kind":"signal","signal":"handle:SIG_POWER_ENABLE"}},
    {"op":"message","external_id":"M_POWER_AVAILABLE","interaction":"handle:INT_STARTUP","name":"PowerAvailable","sort":"AsynchSignal","send":"handle:O5","receive":"handle:O6","signature":{"kind":"signal","signal":"handle:SIG_POWER_AVAILABLE"}},
    {"op":"message","external_id":"M_TORQUE","interaction":"handle:INT_STARTUP","name":"TorqueCommand","sort":"AsynchSignal","send":"handle:O7","receive":"handle:O8","signature":{"kind":"signal","signal":"handle:SIG_TORQUE"}},
    {"op":"message","external_id":"M_READY","interaction":"handle:INT_STARTUP","name":"VehicleReady","sort":"AsynchSignal","send":"handle:O9","receive":"handle:O10","signature":{"kind":"signal","signal":"handle:SIG_READY"}},
    {"op":"parametric_metadata","element":"handle:CB_FORCE","constraint_expression":"F = m * a"},
    {"op":"parametric_metadata","element":"handle:CB_POWER","constraint_expression":"P = F * v"},
    {"op":"parametric_metadata","element":"handle:CB_RANGE","constraint_expression":"R = E / c"},
    {"op":"binding","external_id":"B_FORCE_M","name":"massBinding","owner":"handle:VEH","source":{"role":"handle:V_MASS"},"target":{"role":"handle:C_FORCE","parameter":"handle:CF_M"}},
    {"op":"binding","external_id":"B_FORCE_A","name":"accelerationBinding","owner":"handle:VEH","source":{"role":"handle:V_ACCEL"},"target":{"role":"handle:C_FORCE","parameter":"handle:CF_A"}},
    {"op":"binding","external_id":"B_FORCE_F","name":"tractiveForceBinding","owner":"handle:VEH","source":{"role":"handle:V_FORCE"},"target":{"role":"handle:C_FORCE","parameter":"handle:CF_F"}},
    {"op":"binding","external_id":"B_POWER_F","name":"forceToPowerBinding","owner":"handle:VEH","source":{"role":"handle:V_FORCE"},"target":{"role":"handle:C_POWER","parameter":"handle:CP_F"}},
    {"op":"binding","external_id":"B_POWER_V","name":"speedBinding","owner":"handle:VEH","source":{"role":"handle:V_SPEED"},"target":{"role":"handle:C_POWER","parameter":"handle:CP_V"}},
    {"op":"binding","external_id":"B_POWER_P","name":"electricalPowerBinding","owner":"handle:VEH","source":{"role":"handle:V_POWER"},"target":{"role":"handle:C_POWER","parameter":"handle:CP_P"}},
    {"op":"binding","external_id":"B_RANGE_E","name":"energyBinding","owner":"handle:VEH","source":{"role":"handle:V_ENERGY"},"target":{"role":"handle:C_RANGE","parameter":"handle:CR_E"}},
    {"op":"binding","external_id":"B_RANGE_C","name":"consumptionBinding","owner":"handle:VEH","source":{"role":"handle:V_CONSUMPTION"},"target":{"role":"handle:C_RANGE","parameter":"handle:CR_C"}},
    {"op":"binding","external_id":"B_RANGE_R","name":"rangeBinding","owner":"handle:VEH","source":{"role":"handle:V_RANGE"},"target":{"role":"handle:C_RANGE","parameter":"handle:CR_R"}}
  ],
  "diagrams": [
    {"external_id":"D_PKG","family":"Package","name":"EV Digital Engineering Model Organization","owner":"handle:PKG"},
    {"external_id":"D_REQ","family":"Requirement","name":"Requirements Architecture","owner":"handle:PKG_REQ"},
    {"external_id":"D_VERIFY","family":"Requirement","name":"Verification and Test Traceability","owner":"handle:PKG_VERIFY"},
    {"external_id":"D_UC","family":"Use Case","name":"Operational Use Cases","owner":"handle:PKG_UC","context":"handle:VEH"},
    {"external_id":"D_BDD","family":"BDD","name":"Electric Vehicle System Definition","owner":"handle:PKG_ARCH"},
    {"external_id":"D_IBD","family":"IBD","name":"Electric Vehicle Internal Structure","owner":"handle:PKG_ARCH","context":"handle:VEH"},
    {"external_id":"D_PT_IBD","family":"IBD","name":"Powertrain Internal Structure","owner":"handle:PKG_ARCH","context":"handle:POWERTRAIN"},
    {"external_id":"D_ACT_OPERATE","family":"Activity","name":"Operate Electric Vehicle","owner":"handle:PKG_ACT","semantic":"handle:ACT_OPERATE"},
    {"external_id":"D_ACT_START","family":"Activity","name":"Start Vehicle","owner":"handle:PKG_ACT","semantic":"handle:ACT_START"},
    {"external_id":"D_SM","family":"State Machine","name":"Vehicle Operating Modes","owner":"handle:PKG_STATE","semantic":"handle:SM_VEH"},
    {"external_id":"D_SEQ","family":"Sequence","name":"Vehicle Startup Sequence","owner":"handle:PKG_SEQ","semantic":"handle:INT_STARTUP"},
    {"external_id":"D_PAR","family":"Parametric","name":"Vehicle Performance Analysis","owner":"handle:PKG_ANALYSIS","context":"handle:VEH"}
  ]
}
''')