[package]
name = "systems-modeler-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
systems-modeler-core = { path = "../../../crates/model-core" }
systems-modeler-persistence = { path = "../../../crates/persistence" }
calamine = "0.36.1"
rust_xlsxwriter = "0.92.0"
csv = "1.4.0"
roxmltree = "0.20.0"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
