// Systems-Modeler-Pro PR57 EV demo module: 00-foundation.groovy.
// Import modules in numeric order. Shared source namespace + stable External IDs make reapply idempotent.
modelScript('''
{
  "source_namespace":"demo:ev-digital-engineering:v3",
  "operations": [
    {"op":"element","external_id":"PKG","kind":"Package","name":"Electric Vehicle Digital Engineering Demonstration","owner":"$root","documentation":"Connected MBSE sales demonstration: requirements, architecture, interfaces, behavior, verification, parametrics, runtime occurrences, drill-down, and interchange."},
    {"op":"element","external_id":"PKG_COMMON","kind":"Package","name":"00 Common Library","owner":"handle:PKG","documentation":"Reusable primitives, domain items, interfaces, and common definitions."},
    {"op":"element","external_id":"PKG_REQ","kind":"Package","name":"10 Requirements and Verification","owner":"handle:PKG","documentation":"Stakeholder-to-verification traceability and change-impact demonstration."},
    {"op":"element","external_id":"PKG_UC","kind":"Package","name":"20 Use Cases","owner":"handle:PKG","documentation":"Operational intent, actors, includes/extends/generalization, and architecture allocation."},
    {"op":"element","external_id":"PKG_ARCH","kind":"Package","name":"30 Architecture","owner":"handle:PKG","documentation":"Multi-level electric-vehicle system, subsystem, component, port, connector, and ItemFlow architecture."},
    {"op":"element","external_id":"PKG_BEHAVIOR","kind":"Package","name":"40 Behavior","owner":"handle:PKG","documentation":"Executable activities, state machines, sequences, operations, receptions, and signals."},
    {"op":"element","external_id":"PKG_PARAM","kind":"Package","name":"50 Parametrics and Analysis","owner":"handle:PKG","documentation":"Executable engineering equations bound to real ValueProperties."},
    {"op":"element","external_id":"PKG_CONFIG","kind":"Package","name":"60 Configurations and Runtime","owner":"handle:PKG","documentation":"Repeated vehicle occurrences used for structural/runtime isolation demonstrations."},
    {"op":"element","external_id":"PKG_TYPES","kind":"Package","name":"Types","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_INTERFACES","kind":"Package","name":"Interface Definitions","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_ITEMS","kind":"Package","name":"Domain Items and Signals","owner":"handle:PKG_COMMON"},
    {"op":"element","external_id":"PKG_REQ_STK","kind":"Package","name":"Stakeholder Requirements","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_REQ_SYS","kind":"Package","name":"System Requirements","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_REQ_IF","kind":"Package","name":"Interface Requirements","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_REQ_PERF","kind":"Package","name":"Performance Requirements","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_REQ_SAFE","kind":"Package","name":"Safety and Reliability Requirements","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_REQ_VER","kind":"Package","name":"Verification Requirements and Test Cases","owner":"handle:PKG_REQ"},
    {"op":"element","external_id":"PKG_ARCH_VEH","kind":"Package","name":"Vehicle","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_PT","kind":"Package","name":"Powertrain","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_ESS","kind":"Package","name":"Energy Storage","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_CTRL","kind":"Package","name":"Controls and HMI","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_THERM","kind":"Package","name":"Thermal","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_BRAKE","kind":"Package","name":"Brakes","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ARCH_SENSOR","kind":"Package","name":"Sensors","owner":"handle:PKG_ARCH"},
    {"op":"element","external_id":"PKG_ACT","kind":"Package","name":"Activities","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_SM","kind":"Package","name":"State Machines","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_SEQ","kind":"Package","name":"Interactions","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"PKG_SIG","kind":"Package","name":"Signals and Events","owner":"handle:PKG_BEHAVIOR"},
    {"op":"element","external_id":"REAL","kind":"PrimitiveType","name":"Real","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"BOOL","kind":"PrimitiveType","name":"Boolean","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"STRING","kind":"PrimitiveType","name":"String","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"VEHICLE_COMPONENT","kind":"Block","name":"VehicleComponent","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"VEHICLE_SUBSYSTEM","kind":"Block","name":"VehicleSubsystem","owner":"handle:PKG_TYPES"},
    {"op":"element","external_id":"IF_HV","kind":"InterfaceBlock","name":"HighVoltagePowerInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_CAN","kind":"InterfaceBlock","name":"VehicleControlBusInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_DRIVER","kind":"InterfaceBlock","name":"DriverCommandInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_BRAKE","kind":"InterfaceBlock","name":"BrakeCommandInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_THERMAL","kind":"InterfaceBlock","name":"ThermalControlInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_CHARGE","kind":"InterfaceBlock","name":"ChargingPowerInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"IF_SERVICE","kind":"InterfaceBlock","name":"ServiceDiagnosticInterface","owner":"handle:PKG_INTERFACES"},
    {"op":"element","external_id":"DT_HV_POWER","kind":"DataType","name":"ElectricalPowerExchange","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_CAN_MSG","kind":"DataType","name":"ControlBusMessage","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_DRIVER_CMD","kind":"DataType","name":"DriverCommand","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_BRAKE_CMD","kind":"DataType","name":"BrakeCommand","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_THERMAL_CMD","kind":"DataType","name":"ThermalCommand","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_CHARGE_POWER","kind":"DataType","name":"ChargingPowerExchange","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"DT_SERVICE_MSG","kind":"DataType","name":"DiagnosticMessage","owner":"handle:PKG_ITEMS"},
    {"op":"element","external_id":"FP_HV_POWER","kind":"FlowProperty","name":"power","owner":"handle:IF_HV","type_ref":"handle:DT_HV_POWER","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_CAN_SIGNAL","kind":"FlowProperty","name":"message","owner":"handle:IF_CAN","type_ref":"handle:DT_CAN_MSG","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_DRIVER_CMD","kind":"FlowProperty","name":"command","owner":"handle:IF_DRIVER","type_ref":"handle:DT_DRIVER_CMD","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_BRAKE_CMD","kind":"FlowProperty","name":"brakeRequest","owner":"handle:IF_BRAKE","type_ref":"handle:DT_BRAKE_CMD","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_THERMAL_CMD","kind":"FlowProperty","name":"coolingRequest","owner":"handle:IF_THERMAL","type_ref":"handle:DT_THERMAL_CMD","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_CHARGE_POWER","kind":"FlowProperty","name":"chargePower","owner":"handle:IF_CHARGE","type_ref":"handle:DT_CHARGE_POWER","flow_direction":"In","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"FP_SERVICE_MSG","kind":"FlowProperty","name":"serviceMessage","owner":"handle:IF_SERVICE","type_ref":"handle:DT_SERVICE_MSG","flow_direction":"Out","multiplicity":{"lower":1,"upper":1}}
  ]
}
''')
