// Systems-Modeler-Pro PR57 EV demo module: 10-architecture-structure.groovy.
// Import modules in numeric order. Shared source namespace + stable External IDs make reapply idempotent.
modelScript('''
{
  "source_namespace":"demo:ev-digital-engineering:v3",
  "operations": [
    {"op":"element","external_id":"VEH","kind":"Block","name":"ElectricVehicle","owner":"ext:PKG_ARCH_VEH","documentation":"Vehicle system context and runtime classifier."},
    {"op":"element","external_id":"PT","kind":"Block","name":"PowertrainSubsystem","owner":"ext:PKG_ARCH_PT","documentation":"Converts electrical power and torque command into traction."},
    {"op":"element","external_id":"ESS","kind":"Block","name":"EnergyStorageSubsystem","owner":"ext:PKG_ARCH_ESS","documentation":"Stores, conditions, charges, and protects traction energy."},
    {"op":"element","external_id":"CTRL","kind":"Block","name":"VehicleControlSubsystem","owner":"ext:PKG_ARCH_CTRL","documentation":"Supervisory control and command routing."},
    {"op":"element","external_id":"HMI","kind":"Block","name":"DriverHMI","owner":"ext:PKG_ARCH_CTRL","documentation":"Driver commands, status, and warnings."},
    {"op":"element","external_id":"TMS","kind":"Block","name":"ThermalManagementSubsystem","owner":"ext:PKG_ARCH_THERM","documentation":"Controls heat rejection and battery/powertrain thermal margin."},
    {"op":"element","external_id":"BRAKES","kind":"Block","name":"BrakeSystem","owner":"ext:PKG_ARCH_BRAKE","documentation":"Executes service and emergency braking commands."},
    {"op":"element","external_id":"SENS","kind":"Block","name":"SensorSuite","owner":"ext:PKG_ARCH_SENSOR","documentation":"Aggregates wheel speed, battery temperature, and accelerator sensing."},
    {"op":"element","external_id":"MOTOR","kind":"Block","name":"TractionMotor","owner":"ext:PKG_ARCH_PT","documentation":"Electric traction motor."},
    {"op":"element","external_id":"INV","kind":"Block","name":"TractionInverter","owner":"ext:PKG_ARCH_PT","documentation":"Converts high-voltage DC to commanded motor drive."},
    {"op":"element","external_id":"BAT","kind":"Block","name":"BatteryPack","owner":"ext:PKG_ARCH_ESS","documentation":"Traction battery energy storage."},
    {"op":"element","external_id":"BMS","kind":"Block","name":"BatteryManagementSystem","owner":"ext:PKG_ARCH_ESS","documentation":"Battery protection, contactor, SOC and thermal monitoring."},
    {"op":"element","external_id":"CHARGER","kind":"Block","name":"OnboardCharger","owner":"ext:PKG_ARCH_ESS","documentation":"Converts external charging power into controlled battery charging."},
    {"op":"element","external_id":"VCU","kind":"Block","name":"VehicleControlUnit","owner":"ext:PKG_ARCH_CTRL","documentation":"Vehicle supervisory controller."},
    {"op":"element","external_id":"THERM_CTRL","kind":"Block","name":"ThermalController","owner":"ext:PKG_ARCH_THERM","documentation":"Supervises cooling operation."},
    {"op":"element","external_id":"PUMP","kind":"Block","name":"CoolantPump","owner":"ext:PKG_ARCH_THERM","documentation":"Circulates coolant."},
    {"op":"element","external_id":"RADIATOR","kind":"Block","name":"Radiator","owner":"ext:PKG_ARCH_THERM","documentation":"Rejects heat to ambient."},
    {"op":"element","external_id":"BRAKE_CTRL","kind":"Block","name":"BrakeController","owner":"ext:PKG_ARCH_BRAKE","documentation":"Supervises brake torque and fail-safe response."},
    {"op":"element","external_id":"BRAKE_ACT","kind":"Block","name":"BrakeActuator","owner":"ext:PKG_ARCH_BRAKE","documentation":"Applies commanded braking force."},
    {"op":"element","external_id":"WHEEL_SENSOR","kind":"Block","name":"WheelSpeedSensor","owner":"ext:PKG_ARCH_SENSOR","documentation":"Measures wheel/vehicle speed."},
    {"op":"element","external_id":"TEMP_SENSOR","kind":"Block","name":"BatteryTemperatureSensor","owner":"ext:PKG_ARCH_SENSOR","documentation":"Measures battery temperature."},
    {"op":"element","external_id":"PEDAL_SENSOR","kind":"Block","name":"AcceleratorPedalSensor","owner":"ext:PKG_ARCH_SENSOR","documentation":"Measures accelerator demand."},
    {"op":"relationship","external_id":"G_PT_SUB","kind":"Generalization","source":"handle:PT","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_ESS_SUB","kind":"Generalization","source":"handle:ESS","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_CTRL_SUB","kind":"Generalization","source":"handle:CTRL","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_TMS_SUB","kind":"Generalization","source":"handle:TMS","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_BRAKES_SUB","kind":"Generalization","source":"handle:BRAKES","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_SENS_SUB","kind":"Generalization","source":"handle:SENS","target":"ext:VEHICLE_SUBSYSTEM","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_HMI_COMP","kind":"Generalization","source":"handle:HMI","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_MOTOR_COMP","kind":"Generalization","source":"handle:MOTOR","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_INV_COMP","kind":"Generalization","source":"handle:INV","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_BAT_COMP","kind":"Generalization","source":"handle:BAT","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_BMS_COMP","kind":"Generalization","source":"handle:BMS","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_CHARGER_COMP","kind":"Generalization","source":"handle:CHARGER","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_VCU_COMP","kind":"Generalization","source":"handle:VCU","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_THERM_CTRL_COMP","kind":"Generalization","source":"handle:THERM_CTRL","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_PUMP_COMP","kind":"Generalization","source":"handle:PUMP","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_RADIATOR_COMP","kind":"Generalization","source":"handle:RADIATOR","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_BRAKE_CTRL_COMP","kind":"Generalization","source":"handle:BRAKE_CTRL","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_BRAKE_ACT_COMP","kind":"Generalization","source":"handle:BRAKE_ACT","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_WHEEL_SENSOR_COMP","kind":"Generalization","source":"handle:WHEEL_SENSOR","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_TEMP_SENSOR_COMP","kind":"Generalization","source":"handle:TEMP_SENSOR","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"relationship","external_id":"G_PEDAL_SENSOR_COMP","kind":"Generalization","source":"handle:PEDAL_SENSOR","target":"ext:VEHICLE_COMPONENT","owner":"ext:PKG_ARCH"},
    {"op":"element","external_id":"P_PT","kind":"PartProperty","name":"powertrain","owner":"handle:VEH","type_ref":"handle:PT","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_ESS","kind":"PartProperty","name":"energyStorage","owner":"handle:VEH","type_ref":"handle:ESS","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_CTRL","kind":"PartProperty","name":"controls","owner":"handle:VEH","type_ref":"handle:CTRL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_HMI","kind":"PartProperty","name":"hmi","owner":"handle:VEH","type_ref":"handle:HMI","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_TMS","kind":"PartProperty","name":"thermal","owner":"handle:VEH","type_ref":"handle:TMS","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BRAKES","kind":"PartProperty","name":"brakes","owner":"handle:VEH","type_ref":"handle:BRAKES","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_SENS","kind":"PartProperty","name":"sensors","owner":"handle:VEH","type_ref":"handle:SENS","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_INV","kind":"PartProperty","name":"inverter","owner":"handle:PT","type_ref":"handle:INV","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_MOTOR","kind":"PartProperty","name":"motor","owner":"handle:PT","type_ref":"handle:MOTOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BAT","kind":"PartProperty","name":"batteryPack","owner":"handle:ESS","type_ref":"handle:BAT","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BMS","kind":"PartProperty","name":"bms","owner":"handle:ESS","type_ref":"handle:BMS","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_CHARGER","kind":"PartProperty","name":"charger","owner":"handle:ESS","type_ref":"handle:CHARGER","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_VCU","kind":"PartProperty","name":"vcu","owner":"handle:CTRL","type_ref":"handle:VCU","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_THERM_CTRL","kind":"PartProperty","name":"controller","owner":"handle:TMS","type_ref":"handle:THERM_CTRL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_PUMP","kind":"PartProperty","name":"pump","owner":"handle:TMS","type_ref":"handle:PUMP","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_RAD","kind":"PartProperty","name":"radiator","owner":"handle:TMS","type_ref":"handle:RADIATOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BRAKE_CTRL","kind":"PartProperty","name":"controller","owner":"handle:BRAKES","type_ref":"handle:BRAKE_CTRL","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_BRAKE_ACT","kind":"PartProperty","name":"actuator","owner":"handle:BRAKES","type_ref":"handle:BRAKE_ACT","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_WHEEL","kind":"PartProperty","name":"wheelSpeed","owner":"handle:SENS","type_ref":"handle:WHEEL_SENSOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_TEMP","kind":"PartProperty","name":"batteryTemperature","owner":"handle:SENS","type_ref":"handle:TEMP_SENSOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_PEDAL","kind":"PartProperty","name":"acceleratorPedal","owner":"handle:SENS","type_ref":"handle:PEDAL_SENSOR","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"R_SERVICE_TOOL","kind":"ReferenceProperty","name":"externalServiceTool","owner":"handle:VEH","type_ref":"handle:HMI","multiplicity":{"lower":0,"upper":1}},
    {"op":"element","external_id":"EV_CHARGE","kind":"ProxyPort","name":"charge","owner":"handle:VEH","type_ref":"ext:IF_CHARGE","is_conjugated":false},
    {"op":"element","external_id":"EV_SERVICE","kind":"FullPort","name":"service","owner":"handle:VEH","type_ref":"ext:IF_SERVICE"},
    {"op":"element","external_id":"PT_HV","kind":"ProxyPort","name":"hvIn","owner":"handle:PT","type_ref":"ext:IF_HV","is_conjugated":true},
    {"op":"element","external_id":"PT_CAN","kind":"ProxyPort","name":"control","owner":"handle:PT","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"ESS_HV","kind":"ProxyPort","name":"hvOut","owner":"handle:ESS","type_ref":"ext:IF_HV","is_conjugated":false},
    {"op":"element","external_id":"ESS_CAN","kind":"ProxyPort","name":"control","owner":"handle:ESS","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"ESS_CHARGE","kind":"ProxyPort","name":"chargeIn","owner":"handle:ESS","type_ref":"ext:IF_CHARGE","is_conjugated":true},
    {"op":"element","external_id":"CTRL_DRIVER","kind":"ProxyPort","name":"driverCommand","owner":"handle:CTRL","type_ref":"ext:IF_DRIVER","is_conjugated":true},
    {"op":"element","external_id":"CTRL_PT","kind":"ProxyPort","name":"powertrainCommand","owner":"handle:CTRL","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"CTRL_ESS","kind":"ProxyPort","name":"energyCommand","owner":"handle:CTRL","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"CTRL_SENSOR","kind":"ProxyPort","name":"sensorData","owner":"handle:CTRL","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"CTRL_BRAKE","kind":"ProxyPort","name":"brakeCommand","owner":"handle:CTRL","type_ref":"ext:IF_BRAKE","is_conjugated":false},
    {"op":"element","external_id":"CTRL_THERM","kind":"ProxyPort","name":"thermalCommand","owner":"handle:CTRL","type_ref":"ext:IF_THERMAL","is_conjugated":false},
    {"op":"element","external_id":"CTRL_SERVICE","kind":"FullPort","name":"service","owner":"handle:CTRL","type_ref":"ext:IF_SERVICE"},
    {"op":"element","external_id":"HMI_DRIVER","kind":"ProxyPort","name":"driverCommand","owner":"handle:HMI","type_ref":"ext:IF_DRIVER","is_conjugated":false},
    {"op":"element","external_id":"HMI_SERVICE","kind":"FullPort","name":"service","owner":"handle:HMI","type_ref":"ext:IF_SERVICE"},
    {"op":"element","external_id":"TMS_CMD","kind":"ProxyPort","name":"control","owner":"handle:TMS","type_ref":"ext:IF_THERMAL","is_conjugated":true},
    {"op":"element","external_id":"BRAKE_CMD","kind":"ProxyPort","name":"control","owner":"handle:BRAKES","type_ref":"ext:IF_BRAKE","is_conjugated":true},
    {"op":"element","external_id":"SENS_CAN","kind":"ProxyPort","name":"telemetry","owner":"handle:SENS","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"INV_HV","kind":"ProxyPort","name":"hvIn","owner":"handle:INV","type_ref":"ext:IF_HV","is_conjugated":true},
    {"op":"element","external_id":"INV_MOTOR","kind":"ProxyPort","name":"motorPower","owner":"handle:INV","type_ref":"ext:IF_HV","is_conjugated":false},
    {"op":"element","external_id":"INV_CAN","kind":"ProxyPort","name":"command","owner":"handle:INV","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"MOTOR_POWER","kind":"ProxyPort","name":"powerIn","owner":"handle:MOTOR","type_ref":"ext:IF_HV","is_conjugated":true},
    {"op":"element","external_id":"BAT_HV","kind":"ProxyPort","name":"hv","owner":"handle:BAT","type_ref":"ext:IF_HV","is_conjugated":false},
    {"op":"element","external_id":"BAT_CHARGE","kind":"ProxyPort","name":"charge","owner":"handle:BAT","type_ref":"ext:IF_CHARGE","is_conjugated":true},
    {"op":"element","external_id":"BMS_CAN","kind":"ProxyPort","name":"control","owner":"handle:BMS","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"CHARGER_EXT","kind":"ProxyPort","name":"chargeIn","owner":"handle:CHARGER","type_ref":"ext:IF_CHARGE","is_conjugated":true},
    {"op":"element","external_id":"CHARGER_BAT","kind":"ProxyPort","name":"batteryOut","owner":"handle:CHARGER","type_ref":"ext:IF_CHARGE","is_conjugated":false},
    {"op":"element","external_id":"VCU_DRIVER","kind":"ProxyPort","name":"driverCommand","owner":"handle:VCU","type_ref":"ext:IF_DRIVER","is_conjugated":true},
    {"op":"element","external_id":"VCU_PT","kind":"ProxyPort","name":"powertrain","owner":"handle:VCU","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"VCU_ESS","kind":"ProxyPort","name":"energyStorage","owner":"handle:VCU","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"VCU_SENSOR","kind":"ProxyPort","name":"sensors","owner":"handle:VCU","type_ref":"ext:IF_CAN","is_conjugated":true},
    {"op":"element","external_id":"VCU_BRAKE","kind":"ProxyPort","name":"brakes","owner":"handle:VCU","type_ref":"ext:IF_BRAKE","is_conjugated":false},
    {"op":"element","external_id":"VCU_THERM","kind":"ProxyPort","name":"thermal","owner":"handle:VCU","type_ref":"ext:IF_THERMAL","is_conjugated":false},
    {"op":"element","external_id":"VCU_SERVICE","kind":"FullPort","name":"service","owner":"handle:VCU","type_ref":"ext:IF_SERVICE"},
    {"op":"element","external_id":"THERM_CAN","kind":"ProxyPort","name":"command","owner":"handle:THERM_CTRL","type_ref":"ext:IF_THERMAL","is_conjugated":true},
    {"op":"element","external_id":"PUMP_CAN","kind":"ProxyPort","name":"command","owner":"handle:PUMP","type_ref":"ext:IF_THERMAL","is_conjugated":true},
    {"op":"element","external_id":"BRAKE_CTRL_CMD","kind":"ProxyPort","name":"command","owner":"handle:BRAKE_CTRL","type_ref":"ext:IF_BRAKE","is_conjugated":true},
    {"op":"element","external_id":"BRAKE_ACT_CMD","kind":"ProxyPort","name":"command","owner":"handle:BRAKE_ACT","type_ref":"ext:IF_BRAKE","is_conjugated":true},
    {"op":"element","external_id":"WHEEL_CAN","kind":"ProxyPort","name":"telemetry","owner":"handle:WHEEL_SENSOR","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"TEMP_CAN","kind":"ProxyPort","name":"telemetry","owner":"handle:TEMP_SENSOR","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"PEDAL_CAN","kind":"ProxyPort","name":"telemetry","owner":"handle:PEDAL_SENSOR","type_ref":"ext:IF_CAN","is_conjugated":false},
    {"op":"element","external_id":"BAT_CAN","kind":"ProxyPort","name":"control","owner":"handle:BAT","type_ref":"ext:IF_CAN","is_conjugated":true}
  ]
}
''')
