// Systems-Modeler-Pro PR57 EV demo module: 40-core-activities.groovy.
// Import modules in numeric order. Shared source namespace + stable External IDs make reapply idempotent.
modelScript('''
{
  "source_namespace":"demo:ev-digital-engineering:v3",
  "operations": [
    {"op":"activity","external_id":"ACT_PREFLIGHT","name":"PerformPreflightChecks","owner":"ext:PKG_ACT","context":"ext:VEH"},
    {"op":"activity_partition","external_id":"PART_PF_VCU","activity":"handle:ACT_PREFLIGHT","name":"Vehicle Control Unit","represented_element":"ext:VCU"},
    {"op":"activity_node","external_id":"PF_INIT","activity":"handle:ACT_PREFLIGHT","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"PF_DIAG","activity":"handle:ACT_PREFLIGHT","name":"Run Diagnostics","node":{"kind":"call_operation","operation":"ext:OP_DIAG"},"partition":"handle:PART_PF_VCU"},
    {"op":"activity_node","external_id":"PF_DEC","activity":"handle:ACT_PREFLIGHT","name":"Preflight Valid?","node":{"kind":"decision"},"partition":"handle:PART_PF_VCU"},
    {"op":"activity_node","external_id":"PF_PASS","activity":"handle:ACT_PREFLIGHT","name":"Preflight Passed","node":{"kind":"opaque_action","body":"true"},"partition":"handle:PART_PF_VCU"},
    {"op":"activity_node","external_id":"PF_FAIL","activity":"handle:ACT_PREFLIGHT","name":"Record Preflight Failure","node":{"kind":"opaque_action","body":"false"},"partition":"handle:PART_PF_VCU"},
    {"op":"activity_node","external_id":"PF_FINAL","activity":"handle:ACT_PREFLIGHT","name":"Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"PF_E1","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_INIT","target":"handle:PF_DIAG"},
    {"op":"activity_edge","external_id":"PF_E2","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_DIAG","target":"handle:PF_DEC"},
    {"op":"activity_edge","external_id":"PF_E3","activity":"handle:ACT_PREFLIGHT","name":"valid","kind":"ControlFlow","source":"handle:PF_DEC","target":"handle:PF_PASS","guard":"true"},
    {"op":"activity_edge","external_id":"PF_E4","activity":"handle:ACT_PREFLIGHT","name":"invalid","kind":"ControlFlow","source":"handle:PF_DEC","target":"handle:PF_FAIL","guard":"false"},
    {"op":"activity_edge","external_id":"PF_E5","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_PASS","target":"handle:PF_FINAL"},
    {"op":"activity_edge","external_id":"PF_E6","activity":"handle:ACT_PREFLIGHT","name":"","kind":"ControlFlow","source":"handle:PF_FAIL","target":"handle:PF_FINAL"},
    {"op":"activity","external_id":"ACT_START","name":"StartVehicleBehavior","owner":"ext:PKG_ACT","context":"ext:VEH"},
    {"op":"activity_partition","external_id":"PART_ST_HMI","activity":"handle:ACT_START","name":"Driver HMI","represented_element":"ext:HMI"},
    {"op":"activity_partition","external_id":"PART_ST_VCU","activity":"handle:ACT_START","name":"VCU","represented_element":"ext:VCU"},
    {"op":"activity_partition","external_id":"PART_ST_BMS","activity":"handle:ACT_START","name":"BMS","represented_element":"ext:BMS"},
    {"op":"activity_node","external_id":"ST_INIT","activity":"handle:ACT_START","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"ST_ACCEPT","activity":"handle:ACT_START","name":"Accept Start Command","node":{"kind":"accept_event","signal":"ext:SIG_START"},"partition":"handle:PART_ST_HMI"},
    {"op":"activity_node","external_id":"ST_PREFLIGHT","activity":"handle:ACT_START","name":"Perform Preflight Checks","node":{"kind":"call_behavior","activity":"handle:ACT_PREFLIGHT"},"partition":"handle:PART_ST_VCU"},
    {"op":"activity_node","external_id":"ST_STARTOP","activity":"handle:ACT_START","name":"Invoke startVehicle","node":{"kind":"call_operation","operation":"ext:OP_START"},"partition":"handle:PART_ST_VCU"},
    {"op":"activity_node","external_id":"ST_HV","activity":"handle:ACT_START","name":"Enable High Voltage","node":{"kind":"send_signal","signal":"ext:SIG_HV_ENABLE"},"partition":"handle:PART_ST_BMS"},
    {"op":"activity_node","external_id":"ST_READY","activity":"handle:ACT_START","name":"Publish Vehicle Ready","node":{"kind":"send_signal","signal":"ext:SIG_VEH_READY"},"partition":"handle:PART_ST_VCU"},
    {"op":"activity_node","external_id":"ST_FINAL","activity":"handle:ACT_START","name":"Ready","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"ST_E1","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_INIT","target":"handle:ST_ACCEPT"},
    {"op":"activity_edge","external_id":"ST_E2","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_ACCEPT","target":"handle:ST_PREFLIGHT"},
    {"op":"activity_edge","external_id":"ST_E3","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_PREFLIGHT","target":"handle:ST_STARTOP"},
    {"op":"activity_edge","external_id":"ST_E4","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_STARTOP","target":"handle:ST_HV"},
    {"op":"activity_edge","external_id":"ST_E5","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_HV","target":"handle:ST_READY"},
    {"op":"activity_edge","external_id":"ST_E6","activity":"handle:ACT_START","name":"","kind":"ControlFlow","source":"handle:ST_READY","target":"handle:ST_FINAL"},
    {"op":"activity","external_id":"ACT_DRIVE","name":"DriveVehicleBehavior","owner":"ext:PKG_ACT","context":"ext:VEH"},
    {"op":"activity_partition","external_id":"PART_D_PEDAL","activity":"handle:ACT_DRIVE","name":"Pedal Sensor","represented_element":"ext:PEDAL_SENSOR"},
    {"op":"activity_partition","external_id":"PART_D_VCU","activity":"handle:ACT_DRIVE","name":"VCU","represented_element":"ext:VCU"},
    {"op":"activity_partition","external_id":"PART_D_INV","activity":"handle:ACT_DRIVE","name":"Inverter","represented_element":"ext:INV"},
    {"op":"activity_partition","external_id":"PART_D_MOTOR","activity":"handle:ACT_DRIVE","name":"Motor","represented_element":"ext:MOTOR"},
    {"op":"activity_node","external_id":"DR_INIT","activity":"handle:ACT_DRIVE","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"DR_SAMPLE","activity":"handle:ACT_DRIVE","name":"Sample Accelerator Demand","node":{"kind":"opaque_action","body":"pedalPercent"},"partition":"handle:PART_D_PEDAL"},
    {"op":"activity_node","external_id":"DR_CALC","activity":"handle:ACT_DRIVE","name":"Calculate Torque Request","node":{"kind":"call_operation","operation":"ext:OP_TORQUE"},"partition":"handle:PART_D_VCU"},
    {"op":"activity_node","external_id":"DR_INV","activity":"handle:ACT_DRIVE","name":"Enable Inverter Torque","node":{"kind":"call_operation","operation":"ext:OP_INV_ENABLE"},"partition":"handle:PART_D_INV"},
    {"op":"activity_node","external_id":"DR_MOTOR","activity":"handle:ACT_DRIVE","name":"Apply Motor Torque","node":{"kind":"call_operation","operation":"ext:OP_MOTOR_APPLY"},"partition":"handle:PART_D_MOTOR"},
    {"op":"activity_node","external_id":"DR_FINAL","activity":"handle:ACT_DRIVE","name":"Complete Cycle","node":{"kind":"activity_final"}},
    {"op":"pin","external_id":"PIN_PEDAL_OUT","owner_action":"handle:DR_SAMPLE","name":"pedalPercent","direction":"Output","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"pin","external_id":"PIN_CALC_IN","owner_action":"handle:DR_CALC","name":"pedalPercent","direction":"Input","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1},"parameter":"ext:PAR_PEDAL"},
    {"op":"pin","external_id":"PIN_CALC_OUT","owner_action":"handle:DR_CALC","name":"torqueRequest","direction":"Output","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1},"parameter":"ext:PAR_TORQUE"},
    {"op":"pin","external_id":"PIN_INV_IN","owner_action":"handle:DR_INV","name":"requestedTorque","direction":"Input","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1},"parameter":"ext:PAR_INV_TORQUE"},
    {"op":"pin","external_id":"PIN_INV_OUT","owner_action":"handle:DR_INV","name":"commandedTorque","direction":"Output","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1}},
    {"op":"pin","external_id":"PIN_MOTOR_IN","owner_action":"handle:DR_MOTOR","name":"torque","direction":"Input","type_ref":"ext:REAL","multiplicity":{"lower":1,"upper":1},"parameter":"ext:PAR_MOTOR_TORQUE"},
    {"op":"activity_edge","external_id":"DR_C1","activity":"handle:ACT_DRIVE","name":"","kind":"ControlFlow","source":"handle:DR_INIT","target":"handle:DR_SAMPLE"},
    {"op":"activity_edge","external_id":"DR_C2","activity":"handle:ACT_DRIVE","name":"","kind":"ControlFlow","source":"handle:DR_SAMPLE","target":"handle:DR_CALC"},
    {"op":"activity_edge","external_id":"DR_C3","activity":"handle:ACT_DRIVE","name":"","kind":"ControlFlow","source":"handle:DR_CALC","target":"handle:DR_INV"},
    {"op":"activity_edge","external_id":"DR_C4","activity":"handle:ACT_DRIVE","name":"","kind":"ControlFlow","source":"handle:DR_INV","target":"handle:DR_MOTOR"},
    {"op":"activity_edge","external_id":"DR_C5","activity":"handle:ACT_DRIVE","name":"","kind":"ControlFlow","source":"handle:DR_MOTOR","target":"handle:DR_FINAL"},
    {"op":"activity_edge","external_id":"DR_O1","activity":"handle:ACT_DRIVE","name":"pedal demand","kind":"ObjectFlow","source":"handle:PIN_PEDAL_OUT","target":"handle:PIN_CALC_IN","source_is_pin":true,"target_is_pin":true},
    {"op":"activity_edge","external_id":"DR_O2","activity":"handle:ACT_DRIVE","name":"torque request","kind":"ObjectFlow","source":"handle:PIN_CALC_OUT","target":"handle:PIN_INV_IN","source_is_pin":true,"target_is_pin":true},
    {"op":"activity_edge","external_id":"DR_O3","activity":"handle:ACT_DRIVE","name":"torque command","kind":"ObjectFlow","source":"handle:PIN_INV_OUT","target":"handle:PIN_MOTOR_IN","source_is_pin":true,"target_is_pin":true}
  ]
}
''')
