// Systems-Modeler-Pro PR57 EV demo module: 41-extended-activities.groovy.
// Import modules in numeric order. Shared source namespace + stable External IDs make reapply idempotent.
modelScript('''
{
  "source_namespace":"demo:ev-digital-engineering:v3",
  "operations": [
    {"op":"activity","external_id":"ACT_THERMAL","name":"ManageThermalLoad","owner":"ext:PKG_ACT","context":"ext:TMS"},
    {"op":"activity_partition","external_id":"PART_T_SENSOR","activity":"handle:ACT_THERMAL","name":"Battery Temperature Sensor","represented_element":"ext:TEMP_SENSOR"},
    {"op":"activity_partition","external_id":"PART_T_CTRL","activity":"handle:ACT_THERMAL","name":"Thermal Controller","represented_element":"ext:THERM_CTRL"},
    {"op":"activity_partition","external_id":"PART_T_PUMP","activity":"handle:ACT_THERMAL","name":"Coolant Pump","represented_element":"ext:PUMP"},
    {"op":"activity_node","external_id":"TH_INIT","activity":"handle:ACT_THERMAL","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"TH_ACCEPT","activity":"handle:ACT_THERMAL","name":"Accept Battery Temperature","node":{"kind":"accept_event","signal":"ext:SIG_BAT_TEMP"},"partition":"handle:PART_T_SENSOR"},
    {"op":"activity_node","external_id":"TH_DEC","activity":"handle:ACT_THERMAL","name":"Cooling Required?","node":{"kind":"decision","decision_input":"temperature > threshold"},"partition":"handle:PART_T_CTRL"},
    {"op":"activity_node","external_id":"TH_CALL","activity":"handle:ACT_THERMAL","name":"Command Cooling","node":{"kind":"call_operation","operation":"ext:OP_PUMP"},"partition":"handle:PART_T_CTRL"},
    {"op":"activity_node","external_id":"TH_WAIT","activity":"handle:ACT_THERMAL","name":"Continue Monitoring","node":{"kind":"accept_time_event","expression":"1.0"},"partition":"handle:PART_T_CTRL"},
    {"op":"activity_node","external_id":"TH_FINAL","activity":"handle:ACT_THERMAL","name":"Cycle Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"TH_E1","activity":"handle:ACT_THERMAL","name":"","kind":"ControlFlow","source":"handle:TH_INIT","target":"handle:TH_ACCEPT"},
    {"op":"activity_edge","external_id":"TH_E2","activity":"handle:ACT_THERMAL","name":"","kind":"ControlFlow","source":"handle:TH_ACCEPT","target":"handle:TH_DEC"},
    {"op":"activity_edge","external_id":"TH_E3","activity":"handle:ACT_THERMAL","name":"hot","kind":"ControlFlow","source":"handle:TH_DEC","target":"handle:TH_CALL","guard":"true"},
    {"op":"activity_edge","external_id":"TH_E4","activity":"handle:ACT_THERMAL","name":"nominal","kind":"ControlFlow","source":"handle:TH_DEC","target":"handle:TH_WAIT","guard":"false"},
    {"op":"activity_edge","external_id":"TH_E5","activity":"handle:ACT_THERMAL","name":"","kind":"ControlFlow","source":"handle:TH_CALL","target":"handle:TH_FINAL"},
    {"op":"activity_edge","external_id":"TH_E6","activity":"handle:ACT_THERMAL","name":"","kind":"ControlFlow","source":"handle:TH_WAIT","target":"handle:TH_FINAL"},
    {"op":"activity","external_id":"ACT_BRAKE","name":"EmergencyBrakingBehavior","owner":"ext:PKG_ACT","context":"ext:BRAKES"},
    {"op":"activity_partition","external_id":"PART_B_VCU","activity":"handle:ACT_BRAKE","name":"VCU","represented_element":"ext:VCU"},
    {"op":"activity_partition","external_id":"PART_B_CTRL","activity":"handle:ACT_BRAKE","name":"Brake Controller","represented_element":"ext:BRAKE_CTRL"},
    {"op":"activity_partition","external_id":"PART_B_ACT","activity":"handle:ACT_BRAKE","name":"Brake Actuator","represented_element":"ext:BRAKE_ACT"},
    {"op":"activity_node","external_id":"BR_INIT","activity":"handle:ACT_BRAKE","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"BR_ACCEPT","activity":"handle:ACT_BRAKE","name":"Accept Brake Request","node":{"kind":"accept_event","signal":"ext:SIG_BRAKE"},"partition":"handle:PART_B_VCU"},
    {"op":"activity_node","external_id":"BR_CALL","activity":"handle:ACT_BRAKE","name":"Apply Brake","node":{"kind":"call_operation","operation":"ext:OP_BRAKE"},"partition":"handle:PART_B_CTRL"},
    {"op":"activity_node","external_id":"BR_SIGNAL","activity":"handle:ACT_BRAKE","name":"Publish Brake Command","node":{"kind":"send_signal","signal":"ext:SIG_BRAKE"},"partition":"handle:PART_B_ACT"},
    {"op":"activity_node","external_id":"BR_FINAL","activity":"handle:ACT_BRAKE","name":"Braking Active","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"BR_E1","activity":"handle:ACT_BRAKE","name":"","kind":"ControlFlow","source":"handle:BR_INIT","target":"handle:BR_ACCEPT"},
    {"op":"activity_edge","external_id":"BR_E2","activity":"handle:ACT_BRAKE","name":"","kind":"ControlFlow","source":"handle:BR_ACCEPT","target":"handle:BR_CALL"},
    {"op":"activity_edge","external_id":"BR_E3","activity":"handle:ACT_BRAKE","name":"","kind":"ControlFlow","source":"handle:BR_CALL","target":"handle:BR_SIGNAL"},
    {"op":"activity_edge","external_id":"BR_E4","activity":"handle:ACT_BRAKE","name":"","kind":"ControlFlow","source":"handle:BR_SIGNAL","target":"handle:BR_FINAL"},
    {"op":"activity","external_id":"ACT_CHARGE","name":"ChargeVehicleBehavior","owner":"ext:PKG_ACT","context":"ext:ESS"},
    {"op":"activity_partition","external_id":"PART_C_BMS","activity":"handle:ACT_CHARGE","name":"BMS","represented_element":"ext:BMS"},
    {"op":"activity_partition","external_id":"PART_C_CHG","activity":"handle:ACT_CHARGE","name":"Onboard Charger","represented_element":"ext:CHARGER"},
    {"op":"activity_partition","external_id":"PART_C_BAT","activity":"handle:ACT_CHARGE","name":"Battery Pack","represented_element":"ext:BAT"},
    {"op":"activity_node","external_id":"CH_INIT","activity":"handle:ACT_CHARGE","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"CH_ACCEPT","activity":"handle:ACT_CHARGE","name":"Accept Charge Request","node":{"kind":"accept_event","signal":"ext:SIG_CHARGE"},"partition":"handle:PART_C_BMS"},
    {"op":"activity_node","external_id":"CH_CALL","activity":"handle:ACT_CHARGE","name":"Start Charge","node":{"kind":"call_operation","operation":"ext:OP_CHARGE"},"partition":"handle:PART_C_BMS"},
    {"op":"activity_node","external_id":"CH_MON","activity":"handle:ACT_CHARGE","name":"Monitor Charge State","node":{"kind":"opaque_action","body":"true"},"partition":"handle:PART_C_BAT"},
    {"op":"activity_node","external_id":"CH_FINAL","activity":"handle:ACT_CHARGE","name":"Charge Session Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"CH_E1","activity":"handle:ACT_CHARGE","name":"","kind":"ControlFlow","source":"handle:CH_INIT","target":"handle:CH_ACCEPT"},
    {"op":"activity_edge","external_id":"CH_E2","activity":"handle:ACT_CHARGE","name":"","kind":"ControlFlow","source":"handle:CH_ACCEPT","target":"handle:CH_CALL"},
    {"op":"activity_edge","external_id":"CH_E3","activity":"handle:ACT_CHARGE","name":"","kind":"ControlFlow","source":"handle:CH_CALL","target":"handle:CH_MON"},
    {"op":"activity_edge","external_id":"CH_E4","activity":"handle:ACT_CHARGE","name":"","kind":"ControlFlow","source":"handle:CH_MON","target":"handle:CH_FINAL"},
    {"op":"activity","external_id":"ACT_STOP","name":"StopVehicleBehavior","owner":"ext:PKG_ACT","context":"ext:VEH"},
    {"op":"activity_partition","external_id":"PART_SP_VCU","activity":"handle:ACT_STOP","name":"Vehicle Control Unit","represented_element":"ext:VCU"},
    {"op":"activity_node","external_id":"SP_INIT","activity":"handle:ACT_STOP","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"SP_ACCEPT","activity":"handle:ACT_STOP","name":"Accept Stop Command","node":{"kind":"accept_event","signal":"ext:SIG_STOP"},"partition":"handle:PART_SP_VCU"},
    {"op":"activity_node","external_id":"SP_CALL","activity":"handle:ACT_STOP","name":"Invoke stopVehicle","node":{"kind":"call_operation","operation":"ext:OP_STOP"},"partition":"handle:PART_SP_VCU"},
    {"op":"activity_node","external_id":"SP_FINAL","activity":"handle:ACT_STOP","name":"Off","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"SP_E1","activity":"handle:ACT_STOP","name":"","kind":"ControlFlow","source":"handle:SP_INIT","target":"handle:SP_ACCEPT"},
    {"op":"activity_edge","external_id":"SP_E2","activity":"handle:ACT_STOP","name":"","kind":"ControlFlow","source":"handle:SP_ACCEPT","target":"handle:SP_CALL"},
    {"op":"activity_edge","external_id":"SP_E3","activity":"handle:ACT_STOP","name":"","kind":"ControlFlow","source":"handle:SP_CALL","target":"handle:SP_FINAL"},
    {"op":"activity","external_id":"ACT_OPERATE","name":"OperateElectricVehicle","owner":"ext:PKG_ACT","context":"ext:VEH"},
    {"op":"activity_partition","external_id":"PART_OP_DRIVER","activity":"handle:ACT_OPERATE","name":"Driver","represented_element":"ext:ACTOR_DRIVER"},
    {"op":"activity_partition","external_id":"PART_OP_VEH","activity":"handle:ACT_OPERATE","name":"Vehicle","represented_element":"ext:VEH"},
    {"op":"activity_node","external_id":"OP_INIT","activity":"handle:ACT_OPERATE","name":"Initial","node":{"kind":"initial"}},
    {"op":"activity_node","external_id":"OP_START_ACT","activity":"handle:ACT_OPERATE","name":"Start Vehicle","node":{"kind":"call_behavior","activity":"ext:ACT_START"},"partition":"handle:PART_OP_VEH"},
    {"op":"activity_node","external_id":"OP_DRIVE_ACT","activity":"handle:ACT_OPERATE","name":"Drive Vehicle","node":{"kind":"call_behavior","activity":"ext:ACT_DRIVE"},"partition":"handle:PART_OP_VEH"},
    {"op":"activity_node","external_id":"OP_THERM_ACT","activity":"handle:ACT_OPERATE","name":"Manage Thermal Load","node":{"kind":"call_behavior","activity":"handle:ACT_THERMAL"},"partition":"handle:PART_OP_VEH"},
    {"op":"activity_node","external_id":"OP_BRAKE_ACT","activity":"handle:ACT_OPERATE","name":"Emergency Braking","node":{"kind":"call_behavior","activity":"handle:ACT_BRAKE"},"partition":"handle:PART_OP_VEH"},
    {"op":"activity_node","external_id":"OP_STOP_ACT","activity":"handle:ACT_OPERATE","name":"Stop Vehicle","node":{"kind":"call_behavior","activity":"handle:ACT_STOP"},"partition":"handle:PART_OP_VEH"},
    {"op":"activity_node","external_id":"OP_FINAL","activity":"handle:ACT_OPERATE","name":"Complete","node":{"kind":"activity_final"}},
    {"op":"activity_edge","external_id":"OP_E1","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_INIT","target":"handle:OP_START_ACT"},
    {"op":"activity_edge","external_id":"OP_E2","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_START_ACT","target":"handle:OP_DRIVE_ACT"},
    {"op":"activity_edge","external_id":"OP_E3","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_DRIVE_ACT","target":"handle:OP_THERM_ACT"},
    {"op":"activity_edge","external_id":"OP_E4","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_THERM_ACT","target":"handle:OP_BRAKE_ACT"},
    {"op":"activity_edge","external_id":"OP_E5","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_BRAKE_ACT","target":"handle:OP_STOP_ACT"},
    {"op":"activity_edge","external_id":"OP_E6","activity":"handle:ACT_OPERATE","name":"","kind":"ControlFlow","source":"handle:OP_STOP_ACT","target":"handle:OP_FINAL"}
  ]
}
''')
