// Systems-Modeler-Pro PR57 EV demo module: 52-parametrics-runtime-diagrams.groovy.
// Import modules in numeric order. Shared source namespace + stable External IDs make reapply idempotent.
modelScript('''
{
  "source_namespace":"demo:ev-digital-engineering:v3",
  "operations": [
    {"op":"element","external_id":"CB_FORCE","kind":"ConstraintBlock","name":"TractiveForceEquation","owner":"ext:PKG_PARAM","documentation":"Executable analysis: F = m * a"},
    {"op":"element","external_id":"CPF_M","kind":"ConstraintParameter","name":"m","owner":"handle:CB_FORCE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPF_A","kind":"ConstraintParameter","name":"a","owner":"handle:CB_FORCE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPF_F","kind":"ConstraintParameter","name":"F","owner":"handle:CB_FORCE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CP_FORCE","kind":"ConstraintProperty","name":"tractiveForceEquation","owner":"ext:VEH","type_ref":"handle:CB_FORCE","multiplicity":{"lower":1,"upper":1}},
    {"op":"parametric_metadata","element":"handle:CB_FORCE","constraint_expression":"F = m * a"},
    {"op":"binding","external_id":"BF_M","name":"massBinding","owner":"ext:VEH","source":{"role":"ext:V_MASS"},"target":{"role":"handle:CP_FORCE","parameter":"handle:CPF_M"}},
    {"op":"binding","external_id":"BF_A","name":"accelerationBinding","owner":"ext:VEH","source":{"role":"ext:V_ACCEL"},"target":{"role":"handle:CP_FORCE","parameter":"handle:CPF_A"}},
    {"op":"binding","external_id":"BF_F","name":"forceBinding","owner":"ext:VEH","source":{"role":"ext:V_FORCE"},"target":{"role":"handle:CP_FORCE","parameter":"handle:CPF_F"}},
    {"op":"element","external_id":"CB_POWER","kind":"ConstraintBlock","name":"ElectricalPowerEquation","owner":"ext:PKG_PARAM","documentation":"Executable analysis: P = V * I"},
    {"op":"element","external_id":"CPP_V","kind":"ConstraintParameter","name":"V","owner":"handle:CB_POWER","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPP_I","kind":"ConstraintParameter","name":"I","owner":"handle:CB_POWER","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPP_P","kind":"ConstraintParameter","name":"P","owner":"handle:CB_POWER","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CP_POWER","kind":"ConstraintProperty","name":"electricalPowerEquation","owner":"ext:PT","type_ref":"handle:CB_POWER","multiplicity":{"lower":1,"upper":1}},
    {"op":"parametric_metadata","element":"handle:CB_POWER","constraint_expression":"P = V * I"},
    {"op":"binding","external_id":"BP_V","name":"voltageBinding","owner":"ext:PT","source":{"role":"ext:V_VOLT"},"target":{"role":"handle:CP_POWER","parameter":"handle:CPP_V"}},
    {"op":"binding","external_id":"BP_I","name":"currentBinding","owner":"ext:PT","source":{"role":"ext:V_CURR"},"target":{"role":"handle:CP_POWER","parameter":"handle:CPP_I"}},
    {"op":"binding","external_id":"BP_P","name":"powerBinding","owner":"ext:PT","source":{"role":"ext:V_POWER"},"target":{"role":"handle:CP_POWER","parameter":"handle:CPP_P"}},
    {"op":"element","external_id":"CB_RANGE","kind":"ConstraintBlock","name":"RangeEquation","owner":"ext:PKG_PARAM","documentation":"Executable analysis: R = E / C"},
    {"op":"element","external_id":"CPR_E","kind":"ConstraintParameter","name":"E","owner":"handle:CB_RANGE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPR_C","kind":"ConstraintParameter","name":"C","owner":"handle:CB_RANGE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPR_R","kind":"ConstraintParameter","name":"R","owner":"handle:CB_RANGE","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CP_RANGE","kind":"ConstraintProperty","name":"rangeEquation","owner":"ext:VEH","type_ref":"handle:CB_RANGE","multiplicity":{"lower":1,"upper":1}},
    {"op":"parametric_metadata","element":"handle:CB_RANGE","constraint_expression":"R = E / C"},
    {"op":"binding","external_id":"BR_E","name":"energyBinding","owner":"ext:VEH","source":{"role":"ext:V_ENERGY"},"target":{"role":"handle:CP_RANGE","parameter":"handle:CPR_E"}},
    {"op":"binding","external_id":"BR_C","name":"consumptionBinding","owner":"ext:VEH","source":{"role":"ext:V_CONS"},"target":{"role":"handle:CP_RANGE","parameter":"handle:CPR_C"}},
    {"op":"binding","external_id":"BR_R","name":"rangeBinding","owner":"ext:VEH","source":{"role":"ext:V_RANGE"},"target":{"role":"handle:CP_RANGE","parameter":"handle:CPR_R"}},
    {"op":"element","external_id":"CB_THERM","kind":"ConstraintBlock","name":"ThermalMarginEquation","owner":"ext:PKG_PARAM","documentation":"Executable analysis: M = L - Q"},
    {"op":"element","external_id":"CPT_L","kind":"ConstraintParameter","name":"L","owner":"handle:CB_THERM","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPT_Q","kind":"ConstraintParameter","name":"Q","owner":"handle:CB_THERM","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CPT_M","kind":"ConstraintParameter","name":"M","owner":"handle:CB_THERM","type_ref":"ext:REAL"},
    {"op":"element","external_id":"CP_THERM","kind":"ConstraintProperty","name":"thermalMarginEquation","owner":"ext:TMS","type_ref":"handle:CB_THERM","multiplicity":{"lower":1,"upper":1}},
    {"op":"parametric_metadata","element":"handle:CB_THERM","constraint_expression":"M = L - Q"},
    {"op":"binding","external_id":"BT_L","name":"coolingCapacityBinding","owner":"ext:TMS","source":{"role":"ext:V_COOL"},"target":{"role":"handle:CP_THERM","parameter":"handle:CPT_L"}},
    {"op":"binding","external_id":"BT_Q","name":"heatLoadBinding","owner":"ext:TMS","source":{"role":"ext:V_HEAT"},"target":{"role":"handle:CP_THERM","parameter":"handle:CPT_Q"}},
    {"op":"binding","external_id":"BT_M","name":"marginBinding","owner":"ext:TMS","source":{"role":"ext:V_MARGIN"},"target":{"role":"handle:CP_THERM","parameter":"handle:CPT_M"}},
    {"op":"relationship","external_id":"REF_FORCE_EQ","kind":"Refine","source":"handle:CB_FORCE","target":"ext:REQ_PERF_FORCE","owner":"ext:PKG_REQ"},
    {"op":"relationship","external_id":"REF_POWER_EQ","kind":"Refine","source":"handle:CB_POWER","target":"ext:REQ_PERF_POWER","owner":"ext:PKG_REQ"},
    {"op":"relationship","external_id":"REF_RANGE_EQ","kind":"Refine","source":"handle:CB_RANGE","target":"ext:REQ_PERF_RANGE","owner":"ext:PKG_REQ"},
    {"op":"relationship","external_id":"REF_THERM_EQ","kind":"Refine","source":"handle:CB_THERM","target":"ext:REQ_PERF_THERM","owner":"ext:PKG_REQ"},
    {"op":"element","external_id":"FLEET","kind":"Block","name":"DemoFleet","owner":"ext:PKG_CONFIG","documentation":"Structural runtime root with two independent ElectricVehicle occurrences for occurrence-specific execution and parametric values."},
    {"op":"element","external_id":"P_VEH_A","kind":"PartProperty","name":"vehicleA","owner":"handle:FLEET","type_ref":"ext:VEH","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"P_VEH_B","kind":"PartProperty","name":"vehicleB","owner":"handle:FLEET","type_ref":"ext:VEH","multiplicity":{"lower":1,"upper":1}},
    {"op":"element","external_id":"SUPPORT_SYS","kind":"Block","name":"FacilitySupportSystem","owner":"ext:PKG_CONFIG","documentation":"Deliberately unrelated branch used to explain out-of-scope change/verification traversal."},
    {"op":"element","external_id":"P_SUPPORT","kind":"PartProperty","name":"supportSystem","owner":"handle:FLEET","type_ref":"handle:SUPPORT_SYS","multiplicity":{"lower":1,"upper":1}},
    {"op":"relationship","external_id":"IMP_ARCH_COMMON","kind":"PackageImport","source":"ext:PKG_ARCH","target":"ext:PKG_COMMON","owner":"ext:PKG_ARCH","name":"reuse common types/interfaces","visibility":"Public"},
    {"op":"relationship","external_id":"IMP_BEHAV_ARCH","kind":"PackageImport","source":"ext:PKG_BEHAVIOR","target":"ext:PKG_ARCH","owner":"ext:PKG_BEHAVIOR","name":"behavior uses architecture","visibility":"Public"},
    {"op":"relationship","external_id":"IMP_PARAM_ARCH","kind":"PackageImport","source":"ext:PKG_PARAM","target":"ext:PKG_ARCH","owner":"ext:PKG_PARAM","name":"analysis constrains architecture","visibility":"Public"},
    {"op":"relationship","external_id":"IMP_REQ_ARCH","kind":"PackageImport","source":"ext:PKG_REQ","target":"ext:PKG_ARCH","owner":"ext:PKG_REQ","name":"requirements trace to architecture","visibility":"Public"}
  ],
  "diagrams": [
    {"external_id":"D_PKG","family":"Package","name":"Digital Engineering Model Organization","owner":"ext:PKG"},
    {"external_id":"D_PKG_REQ","family":"Package","name":"Requirements Organization","owner":"ext:PKG_REQ"},
    {"external_id":"D_PKG_ARCH","family":"Package","name":"Architecture Organization","owner":"ext:PKG_ARCH"},
    {"external_id":"D_PKG_BEHAV","family":"Package","name":"Behavior Organization","owner":"ext:PKG_BEHAVIOR"},
    {"external_id":"D_PKG_PARAM","family":"Package","name":"Analysis Organization","owner":"ext:PKG_PARAM"},
    {"external_id":"D_BDD_VEH","family":"BDD","name":"Electric Vehicle Definition and Subsystem Decomposition","owner":"ext:PKG_ARCH_VEH"},
    {"external_id":"D_BDD_PT","family":"BDD","name":"Powertrain Definitions","owner":"ext:PKG_ARCH_PT"},
    {"external_id":"D_BDD_ESS","family":"BDD","name":"Energy Storage Definitions","owner":"ext:PKG_ARCH_ESS"},
    {"external_id":"D_BDD_CTRL","family":"BDD","name":"Controls and HMI Definitions","owner":"ext:PKG_ARCH_CTRL"},
    {"external_id":"D_BDD_THERM","family":"BDD","name":"Thermal Definitions","owner":"ext:PKG_ARCH_THERM"},
    {"external_id":"D_BDD_BRAKE","family":"BDD","name":"Brake Definitions","owner":"ext:PKG_ARCH_BRAKE"},
    {"external_id":"D_BDD_SENSOR","family":"BDD","name":"Sensor Definitions","owner":"ext:PKG_ARCH_SENSOR"},
    {"external_id":"D_BDD_FLEET","family":"BDD","name":"Runtime Fleet Definition","owner":"ext:PKG_CONFIG"},
    {"external_id":"D_IBD_VEH","family":"IBD","name":"Electric Vehicle Internal Architecture","owner":"ext:PKG_ARCH_VEH","context":"ext:VEH"},
    {"external_id":"D_IBD_PT","family":"IBD","name":"Powertrain Internal Architecture","owner":"ext:PKG_ARCH_PT","context":"ext:PT"},
    {"external_id":"D_IBD_ESS","family":"IBD","name":"Energy Storage Internal Architecture","owner":"ext:PKG_ARCH_ESS","context":"ext:ESS"},
    {"external_id":"D_IBD_CTRL","family":"IBD","name":"Vehicle Control Internal Architecture","owner":"ext:PKG_ARCH_CTRL","context":"ext:CTRL"},
    {"external_id":"D_IBD_THERM","family":"IBD","name":"Thermal Internal Architecture","owner":"ext:PKG_ARCH_THERM","context":"ext:TMS"},
    {"external_id":"D_IBD_BRAKE","family":"IBD","name":"Brake Internal Architecture","owner":"ext:PKG_ARCH_BRAKE","context":"ext:BRAKES"},
    {"external_id":"D_IBD_SENSOR","family":"IBD","name":"Sensor Suite Internal Architecture","owner":"ext:PKG_ARCH_SENSOR","context":"ext:SENS"},
    {"op":"noop"}
  ]
}
''')
